export default {
    currentHp: 0,
    name: "Dendro Samachurl",
    group: "Hilichurl",
    minExp: 5,
    maxExp: 10,
    minWorldLevel: 9,
    image: "https://lh.elara.workers.dev/rpg/monsters/dendro_samachurl.png",
    drops: [
        { item: "Divining Scroll", minAmount: 1, maxAmount: 2, chance: 90 },
        { item: "Sealed Scroll", minAmount: 1, maxAmount: 1, chance: 75 },
        {
            item: "Forbidden Curse Scroll",
            minAmount: 1,
            maxAmount: 1,
            chance: 50,
        },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],
    locations: ["Nantianmen", "Luhua Pool", "Guili Plains"],

    critChance: 0,
    critValue: 0,
    defChance: 50,
    defValue: 0.25,
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            {
                worldLevel: 9,
                minHp: 348,
                maxHp: 390,
                minDamage: 21,
                maxDamage: 29,
            },
            {
                worldLevel: 10,
                minHp: 390,
                maxHp: 430,
                minDamage: 23,
                maxDamage: 30,
            },
            {
                worldLevel: 11,
                minHp: 420,
                maxHp: 460,
                minDamage: 25,
                maxDamage: 32,
            },
            {
                worldLevel: 12,
                minHp: 465,
                maxHp: 515,
                minDamage: 28,
                maxDamage: 35,
            },
            {
                worldLevel: 13,
                minHp: 515,
                maxHp: 570,
                minDamage: 31,
                maxDamage: 38,
            },
            {
                worldLevel: 14,
                minHp: 570,
                maxHp: 625,
                minDamage: 33,
                maxDamage: 40,
            },
            {
                worldLevel: 15,
                minHp: 625,
                maxHp: 680,
                minDamage: 36,
                maxDamage: 44,
            },
            {
                worldLevel: 16,
                minHp: 680,
                maxHp: 745,
                minDamage: 42,
                maxDamage: 54,
            },
            {
                worldLevel: 17,
                minHp: 745,
                maxHp: 810,
                minDamage: 54,
                maxDamage: 65,
            },
            {
                worldLevel: 18,
                minHp: 810,
                maxHp: 875,
                minDamage: 65,
                maxDamage: 78,
            },
            {
                worldLevel: 19,
                minHp: 875,
                maxHp: 940,
                minDamage: 80,
                maxDamage: 105,
            },
            {
                worldLevel: 20,
                minHp: 980,
                maxHp: 1200,
                minDamage: 90,
                maxDamage: 125,
            },
        ];

        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
