import { MonsterGroup } from "../../monsterHelper";

export default {
    currentHp: 0,
    name: "Ruin Scout",
    group: MonsterGroup.Machine,
    minExp: 5,
    maxExp: 10,
    minWorldLevel: 9,
    image: "https://lh.elara.workers.dev/rpg/monsters/ruin_scout.png",
    drops: [
        {
            item: "Chaos Gear",
            minAmount: 1,
            maxAmount: 1,
            chance: 75,
        },
    ],

    critChance: 10,
    critValue: 2,
    defChance: 25,
    defValue: 0.5,
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            {
                worldLevel: 9,
                minHp: 402,
                maxHp: 465,
                minDamage: 21,
                maxDamage: 29,
            },
            {
                worldLevel: 10,
                minHp: 465,
                maxHp: 525,
                minDamage: 23,
                maxDamage: 30,
            },
            {
                worldLevel: 11,
                minHp: 510,
                maxHp: 570,
                minDamage: 25,
                maxDamage: 32,
            },
            {
                worldLevel: 12,
                minHp: 578,
                maxHp: 653,
                minDamage: 28,
                maxDamage: 35,
            },
            {
                worldLevel: 13,
                minHp: 652,
                maxHp: 735,
                minDamage: 31,
                maxDamage: 38,
            },
            {
                worldLevel: 14,
                minHp: 735,
                maxHp: 818,
                minDamage: 33,
                maxDamage: 40,
            },
            {
                worldLevel: 15,
                minHp: 818,
                maxHp: 900,
                minDamage: 36,
                maxDamage: 44,
            },
            {
                worldLevel: 16,
                minHp: 900,
                maxHp: 998,
                minDamage: 42,
                maxDamage: 54,
            },
            {
                worldLevel: 17,
                minHp: 998,
                maxHp: 1095,
                minDamage: 54,
                maxDamage: 65,
            },
            {
                worldLevel: 18,
                minHp: 1095,
                maxHp: 1193,
                minDamage: 65,
                maxDamage: 78,
            },
            {
                worldLevel: 19,
                minHp: 1193,
                maxHp: 1290,
                minDamage: 80,
                maxDamage: 105,
            },
            {
                worldLevel: 20,
                minHp: 1350,
                maxHp: 1680,
                minDamage: 90,
                maxDamage: 125,
            },
            {
                worldLevel: 21,
                minHp: 900,
                maxHp: 1150,
                minDamage: 95,
                maxDamage: 130,
            },
            {
                worldLevel: 22,
                minHp: 950,
                maxHp: 1200,
                minDamage: 100,
                maxDamage: 135,
            },
            {
                worldLevel: 23,
                minHp: 1000,
                maxHp: 1250,
                minDamage: 105,
                maxDamage: 140,
            },
            {
                worldLevel: 24,
                minHp: 1050,
                maxHp: 1300,
                minDamage: 110,
                maxDamage: 145,
            },
            {
                worldLevel: 25,
                minHp: 1100,
                maxHp: 1350,
                minDamage: 115,
                maxDamage: 150,
            },
        ];
        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
