export default {
    name: "Cryo Hilichurl Shooter",
    group: "Hilichurl",
    hpConstant: 11.5,
    atkConstant: 4.5,
    baseHp: 120,
    baseAtk: 15,
    minExp: 5,
    maxExp: 10,
    minWorldLevel: 6,
    critChance: 25,
    critValue: 1.5,
    defChance: 20,
    defValue: 15,
    image: "https://lh.elara.workers.dev/rpg/monsters/cryo_hilichurl_shooter.png",
    drops: [
        {
            item: "Firm Arrowhead",
            minAmount: 1,
            maxAmount: 3,
            chance: 100,
        },
        {
            item: "Sharp Arrowhead",
            minAmount: 1,
            maxAmount: 2,
            chance: 75,
        },
        {
            item: "Weathered Arrowhead",
            minAmount: 1,
            maxAmount: 2,
            chance: 50,
        },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],
    locations: ["Tianqiu Valley", "Jueyun Karst", "Guili Plains"],
};
