import { MonsterGroup } from "../../groups";

export default {
    currentHp: 0,
    name: "Stonehide Lawachurl",
    group: MonsterGroup.Hilichurl,
    minExp: 5,
    maxExp: 10,
    minWorldLevel: 6,
    critChance: 25,
    critValue: 1.5,
    defChance: 20,
    defValue: 0.2,
    image: "https://lh.elara.workers.dev/rpg/monsters/stonehide_lawachurl.png",
    drops: [
        { item: "Stained Mask", minAmount: 1, maxAmount: 3, chance: 90 },
        { item: "Ominous Mask", minAmount: 1, maxAmount: 2, chance: 75 },
        { item: "Heavy Horn", minAmount: 1, maxAmount: 2, chance: 50 },
        { item: "Black Bronze Horn", minAmount: 1, maxAmount: 2, chance: 25 },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            {
                worldLevel: 6,
                minHp: 125,
                maxHp: 170,
                minDamage: 12,
                maxDamage: 21,
            },
            {
                worldLevel: 7,
                minHp: 170,
                maxHp: 208,
                minDamage: 15,
                maxDamage: 23,
            },
            {
                worldLevel: 8,
                minHp: 208,
                maxHp: 268,
                minDamage: 18,
                maxDamage: 26,
            },
            {
                worldLevel: 9,
                minHp: 268,
                maxHp: 310,
                minDamage: 21,
                maxDamage: 29,
            },
            {
                worldLevel: 10,
                minHp: 310,
                maxHp: 350,
                minDamage: 23,
                maxDamage: 30,
            },
            {
                worldLevel: 11,
                minHp: 340,
                maxHp: 380,
                minDamage: 25,
                maxDamage: 32,
            },
            {
                worldLevel: 12,
                minHp: 385,
                maxHp: 435,
                minDamage: 28,
                maxDamage: 35,
            },
            {
                worldLevel: 13,
                minHp: 435,
                maxHp: 490,
                minDamage: 31,
                maxDamage: 38,
            },
            {
                worldLevel: 14,
                minHp: 490,
                maxHp: 545,
                minDamage: 33,
                maxDamage: 40,
            },
            {
                worldLevel: 15,
                minHp: 545,
                maxHp: 600,
                minDamage: 36,
                maxDamage: 44,
            },
            {
                worldLevel: 16,
                minHp: 600,
                maxHp: 665,
                minDamage: 42,
                maxDamage: 54,
            },
            {
                worldLevel: 17,
                minHp: 665,
                maxHp: 730,
                minDamage: 54,
                maxDamage: 65,
            },
            {
                worldLevel: 18,
                minHp: 730,
                maxHp: 795,
                minDamage: 65,
                maxDamage: 78,
            },
            {
                worldLevel: 19,
                minHp: 795,
                maxHp: 860,
                minDamage: 80,
                maxDamage: 105,
            },
            {
                worldLevel: 20,
                minHp: 900,
                maxHp: 1120,
                minDamage: 90,
                maxDamage: 125,
            },
        ];
        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
