import { MonsterGroup } from "../../monsterHelper";

export default {
    currentHp: 0,
    name: "Geo Slime",
    group: MonsterGroup.Slime,
    minExp: 5,
    maxExp: 10,
    minWorldLevel: 5,
    image: "https://lh.elara.workers.dev/rpg/monsters/geo_slime.png",
    drops: [
        {
            item: "Slime Condensate",
            minAmount: 1,
            maxAmount: 3,
            chance: 90,
        },
        {
            item: "Slime Secretions",
            minAmount: 1,
            maxAmount: 3,
            chance: 50,
        },
        {
            item: "Slime Concentrate",
            minAmount: 1,
            maxAmount: 2,
            chance: 50,
        },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],

    critChance: 10,
    critValue: 1.5,
    defChance: 20,
    defValue: 0.5,
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            {
                worldLevel: 5,
                minHp: 27.5,
                maxHp: 115.5,
                minDamage: 7,
                maxDamage: 12,
            },
            {
                worldLevel: 6,
                minHp: 38.5,
                maxHp: 165,
                minDamage: 8,
                maxDamage: 14,
            },
            {
                worldLevel: 7,
                minHp: 55,
                maxHp: 207,
                minDamage: 10,
                maxDamage: 15,
            },
            {
                worldLevel: 8,
                minHp: 69,
                maxHp: 247.5,
                minDamage: 12,
                maxDamage: 17,
            },
            {
                worldLevel: 9,
                minHp: 82.5,
                maxHp: 289.5,
                minDamage: 14,
                maxDamage: 19,
            },
            {
                worldLevel: 10,
                minHp: 96.5,
                maxHp: 330,
                minDamage: 15,
                maxDamage: 20,
            },
            {
                worldLevel: 11,
                minHp: 110,
                maxHp: 412.5,
                minDamage: 17,
                maxDamage: 23,
            },
            {
                worldLevel: 12,
                minHp: 137.5,
                maxHp: 495,
                minDamage: 20,
                maxDamage: 25,
            },
            {
                worldLevel: 13,
                minHp: 165,
                maxHp: 577.5,
                minDamage: 23,
                maxDamage: 27,
            },
            {
                worldLevel: 14,
                minHp: 192.5,
                maxHp: 660,
                minDamage: 25,
                maxDamage: 30,
            },
            {
                worldLevel: 15,
                minHp: 220,
                maxHp: 742.5,
                minDamage: 27,
                maxDamage: 35,
            },
            {
                worldLevel: 16,
                minHp: 275,
                maxHp: 907.5,
                minDamage: 40,
                maxDamage: 50,
            },
            {
                worldLevel: 17,
                minHp: 302.5,
                maxHp: 990,
                minDamage: 50,
                maxDamage: 60,
            },
            {
                worldLevel: 18,
                minHp: 330,
                maxHp: 1072.5,
                minDamage: 60,
                maxDamage: 75,
            },
            {
                worldLevel: 19,
                minHp: 357.5,
                maxHp: 1155,
                minDamage: 75,
                maxDamage: 100,
            },
            {
                worldLevel: 20,
                minHp: 440,
                maxHp: 1650,
                minDamage: 80,
                maxDamage: 120,
            },
            {
                worldLevel: 21,
                minHp: 490,
                maxHp: 1785,
                minDamage: 85,
                maxDamage: 125,
            },
            {
                worldLevel: 22,
                minHp: 525,
                maxHp: 1920,
                minDamage: 90,
                maxDamage: 130,
            },
            {
                worldLevel: 23,
                minHp: 560,
                maxHp: 2055,
                minDamage: 95,
                maxDamage: 135,
            },
            {
                worldLevel: 24,
                minHp: 595,
                maxHp: 2190,
                minDamage: 100,
                maxDamage: 140,
            },
            {
                worldLevel: 25,
                minHp: 630,
                maxHp: 2325,
                minDamage: 105,
                maxDamage: 145,
            },
        ];
        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
