import { MonsterGroup } from "../../monsterHelper";

export default {
    currentHp: 0,
    name: "Anemo Samachurl",
    group: MonsterGroup.Hilichurl,
    minExp: 5,
    maxExp: 7,
    minWorldLevel: 3,
    image: "https://lh.elara.workers.dev/rpg/monsters/anemo_samachurl.png",
    drops: [
        { item: "Divining Scroll", minAmount: 1, maxAmount: 3, chance: 85 },
        { item: "Sealed Scroll", minAmount: 1, maxAmount: 2, chance: 35 },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],

    critChance: 10,
    critValue: 1.5,
    defChance: 20,
    defValue: 0.2,
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            { worldLevel: 3, minHp: 38, maxHp: 53, minDamage: 6, maxDamage: 9 },
            {
                worldLevel: 4,
                minHp: 53,
                maxHp: 75,
                minDamage: 9,
                maxDamage: 15,
            },
            {
                worldLevel: 5,
                minHp: 82,
                maxHp: 116,
                minDamage: 11,
                maxDamage: 18,
            },
            {
                worldLevel: 6,
                minHp: 105,
                maxHp: 150,
                minDamage: 12,
                maxDamage: 21,
            },
            {
                worldLevel: 7,
                minHp: 150,
                maxHp: 188,
                minDamage: 15,
                maxDamage: 23,
            },
            {
                worldLevel: 8,
                minHp: 188,
                maxHp: 248,
                minDamage: 18,
                maxDamage: 26,
            },
            {
                worldLevel: 9,
                minHp: 248,
                maxHp: 290,
                minDamage: 21,
                maxDamage: 29,
            },
            {
                worldLevel: 10,
                minHp: 290,
                maxHp: 330,
                minDamage: 23,
                maxDamage: 30,
            },
            {
                worldLevel: 11,
                minHp: 320,
                maxHp: 360,
                minDamage: 25,
                maxDamage: 32,
            },
            {
                worldLevel: 12,
                minHp: 365,
                maxHp: 415,
                minDamage: 28,
                maxDamage: 35,
            },
            {
                worldLevel: 13,
                minHp: 415,
                maxHp: 470,
                minDamage: 31,
                maxDamage: 38,
            },
            {
                worldLevel: 14,
                minHp: 470,
                maxHp: 525,
                minDamage: 33,
                maxDamage: 40,
            },
            {
                worldLevel: 15,
                minHp: 525,
                maxHp: 580,
                minDamage: 36,
                maxDamage: 44,
            },
            {
                worldLevel: 16,
                minHp: 780,
                maxHp: 845,
                minDamage: 42,
                maxDamage: 54,
            },
            {
                worldLevel: 17,
                minHp: 745,
                maxHp: 810,
                minDamage: 54,
                maxDamage: 65,
            },
            {
                worldLevel: 18,
                minHp: 810,
                maxHp: 875,
                minDamage: 65,
                maxDamage: 78,
            },
            {
                worldLevel: 19,
                minHp: 875,
                maxHp: 940,
                minDamage: 80,
                maxDamage: 105,
            },
            {
                worldLevel: 20,
                minHp: 980,
                maxHp: 1200,
                minDamage: 90,
                maxDamage: 125,
            },
            {
                worldLevel: 21,
                minHp: 1050,
                maxHp: 1250,
                minDamage: 95,
                maxDamage: 130,
            },
            {
                worldLevel: 22,
                minHp: 1110,
                maxHp: 1320,
                minDamage: 100,
                maxDamage: 135,
            },
            {
                worldLevel: 23,
                minHp: 1170,
                maxHp: 1390,
                minDamage: 105,
                maxDamage: 140,
            },
            {
                worldLevel: 24,
                minHp: 1230,
                maxHp: 1460,
                minDamage: 110,
                maxDamage: 145,
            },
            {
                worldLevel: 25,
                minHp: 1290,
                maxHp: 1530,
                minDamage: 115,
                maxDamage: 150,
            },
        ];

        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
