export default {
    currentHp: 0,
    name: "Cryo Samachurl",
    group: "Hilichurl",
    minExp: 5,
    maxExp: 7,
    minWorldLevel: 3,
    image: "https://lh.elara.workers.dev/rpg/monsters/cryo_samachurl.png",
    drops: [
        { item: "Divining Scroll", minAmount: 1, maxAmount: 2, chance: 80 },
        { item: "Sealed Scroll", minAmount: 1, maxAmount: 1, chance: 45 },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],
    locations: ["Tianqiu Valley", "Jueyun Karst", "Guili Plains"],

    critChance: 10,
    critValue: 1.5,
    defChance: 20,
    defValue: 0.2,
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            { worldLevel: 3, minHp: 38, maxHp: 53, minDamage: 6, maxDamage: 9 },
            {
                worldLevel: 4,
                minHp: 53,
                maxHp: 75,
                minDamage: 9,
                maxDamage: 15,
            },
            {
                worldLevel: 5,
                minHp: 82,
                maxHp: 116,
                minDamage: 11,
                maxDamage: 18,
            },
            {
                worldLevel: 6,
                minHp: 105,
                maxHp: 150,
                minDamage: 12,
                maxDamage: 21,
            },
            {
                worldLevel: 7,
                minHp: 150,
                maxHp: 188,
                minDamage: 15,
                maxDamage: 23,
            },
            {
                worldLevel: 8,
                minHp: 188,
                maxHp: 248,
                minDamage: 18,
                maxDamage: 26,
            },
            {
                worldLevel: 9,
                minHp: 248,
                maxHp: 290,
                minDamage: 21,
                maxDamage: 29,
            },
            {
                worldLevel: 10,
                minHp: 290,
                maxHp: 330,
                minDamage: 23,
                maxDamage: 30,
            },
            {
                worldLevel: 11,
                minHp: 320,
                maxHp: 360,
                minDamage: 25,
                maxDamage: 32,
            },
            {
                worldLevel: 12,
                minHp: 365,
                maxHp: 415,
                minDamage: 28,
                maxDamage: 35,
            },
            {
                worldLevel: 13,
                minHp: 415,
                maxHp: 470,
                minDamage: 31,
                maxDamage: 38,
            },
            {
                worldLevel: 14,
                minHp: 470,
                maxHp: 525,
                minDamage: 33,
                maxDamage: 40,
            },
            {
                worldLevel: 15,
                minHp: 525,
                maxHp: 580,
                minDamage: 36,
                maxDamage: 44,
            },
            {
                worldLevel: 16,
                minHp: 580,
                maxHp: 645,
                minDamage: 42,
                maxDamage: 54,
            },
            {
                worldLevel: 17,
                minHp: 645,
                maxHp: 710,
                minDamage: 54,
                maxDamage: 65,
            },
            {
                worldLevel: 18,
                minHp: 710,
                maxHp: 775,
                minDamage: 65,
                maxDamage: 78,
            },
            {
                worldLevel: 19,
                minHp: 775,
                maxHp: 840,
                minDamage: 80,
                maxDamage: 105,
            },
            {
                worldLevel: 20,
                minHp: 880,
                maxHp: 1100,
                minDamage: 90,
                maxDamage: 125,
            },
        ];

        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
