import { MonsterGroup } from "../../groups";

export default {
    currentHp: 0,
    name: "Mitachurl",
    group: MonsterGroup.Hilichurl,
    minExp: 5,
    maxExp: 7,
    minWorldLevel: 3,
    image: "https://lh.elara.workers.dev/rpg/monsters/mitachurl.png",
    drops: [
        { item: "Stained Mask", minAmount: 1, maxAmount: 2, chance: 90 },
        { item: "Ominous Mask", minAmount: 1, maxAmount: 1, chance: 50 },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],

    critChance: 15,
    critValue: 2,
    defChance: 15,
    defValue: 0.2,
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            { worldLevel: 3, minHp: 58, maxHp: 73, minDamage: 6, maxDamage: 9 },
            {
                worldLevel: 4,
                minHp: 73,
                maxHp: 95,
                minDamage: 9,
                maxDamage: 15,
            },
            {
                worldLevel: 5,
                minHp: 102,
                maxHp: 136,
                minDamage: 11,
                maxDamage: 18,
            },
            {
                worldLevel: 6,
                minHp: 125,
                maxHp: 170,
                minDamage: 12,
                maxDamage: 21,
            },
            {
                worldLevel: 7,
                minHp: 170,
                maxHp: 208,
                minDamage: 15,
                maxDamage: 23,
            },
            {
                worldLevel: 8,
                minHp: 208,
                maxHp: 268,
                minDamage: 18,
                maxDamage: 26,
            },
            {
                worldLevel: 9,
                minHp: 268,
                maxHp: 310,
                minDamage: 21,
                maxDamage: 29,
            },
            {
                worldLevel: 10,
                minHp: 310,
                maxHp: 350,
                minDamage: 23,
                maxDamage: 30,
            },
            {
                worldLevel: 11,
                minHp: 340,
                maxHp: 380,
                minDamage: 25,
                maxDamage: 32,
            },
            {
                worldLevel: 12,
                minHp: 385,
                maxHp: 435,
                minDamage: 28,
                maxDamage: 35,
            },
            {
                worldLevel: 13,
                minHp: 435,
                maxHp: 490,
                minDamage: 31,
                maxDamage: 38,
            },
            {
                worldLevel: 14,
                minHp: 490,
                maxHp: 545,
                minDamage: 33,
                maxDamage: 40,
            },
            {
                worldLevel: 15,
                minHp: 545,
                maxHp: 600,
                minDamage: 36,
                maxDamage: 44,
            },
            {
                worldLevel: 16,
                minHp: 600,
                maxHp: 665,
                minDamage: 42,
                maxDamage: 54,
            },
            {
                worldLevel: 17,
                minHp: 665,
                maxHp: 730,
                minDamage: 54,
                maxDamage: 65,
            },
            {
                worldLevel: 18,
                minHp: 730,
                maxHp: 795,
                minDamage: 65,
                maxDamage: 78,
            },
            {
                worldLevel: 19,
                minHp: 795,
                maxHp: 860,
                minDamage: 80,
                maxDamage: 105,
            },
            {
                worldLevel: 20,
                minHp: 900,
                maxHp: 1120,
                minDamage: 90,
                maxDamage: 125,
            },
            {
                worldLevel: 21,
                minHp: 950,
                maxHp: 1150,
                minDamage: 95,
                maxDamage: 130,
            },
            {
                worldLevel: 22,
                minHp: 1000,
                maxHp: 1200,
                minDamage: 100,
                maxDamage: 135,
            },
            {
                worldLevel: 23,
                minHp: 1050,
                maxHp: 1250,
                minDamage: 105,
                maxDamage: 140,
            },
            {
                worldLevel: 24,
                minHp: 1100,
                maxHp: 1300,
                minDamage: 110,
                maxDamage: 145,
            },
            {
                worldLevel: 25,
                minHp: 1150,
                maxHp: 1350,
                minDamage: 115,
                maxDamage: 150,
            },
        ];
        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
