import { MonsterGroup } from "../../monsterHelper";

export default {
    currentHp: 0,
    name: "Pyro Hilichurl Berserker",
    group: MonsterGroup.Hilichurl,
    minExp: 4,
    maxExp: 8,
    minWorldLevel: 2,
    image: "https://lh.elara.workers.dev/rpg/monsters/pyro_hilichurl_berserker.png",
    drops: [
        { item: "Damaged Mask", minAmount: 1, maxAmount: 2, chance: 90 },
        { item: "Stained Mask", minAmount: 1, maxAmount: 2, chance: 75 },
        { item: "Ominous Mask", minAmount: 1, maxAmount: 1, chance: 25 },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],

    critChance: 10,
    critValue: 1.5,
    defChance: 20,
    defValue: 0.2,
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            { worldLevel: 2, minHp: 25, maxHp: 38, minDamage: 4, maxDamage: 6 },
            { worldLevel: 3, minHp: 38, maxHp: 53, minDamage: 6, maxDamage: 9 },
            {
                worldLevel: 4,
                minHp: 53,
                maxHp: 75,
                minDamage: 9,
                maxDamage: 15,
            },
            {
                worldLevel: 5,
                minHp: 82,
                maxHp: 116,
                minDamage: 11,
                maxDamage: 18,
            },
            {
                worldLevel: 6,
                minHp: 105,
                maxHp: 150,
                minDamage: 12,
                maxDamage: 21,
            },
            {
                worldLevel: 7,
                minHp: 150,
                maxHp: 188,
                minDamage: 15,
                maxDamage: 23,
            },
            {
                worldLevel: 8,
                minHp: 188,
                maxHp: 248,
                minDamage: 18,
                maxDamage: 26,
            },
            {
                worldLevel: 9,
                minHp: 248,
                maxHp: 290,
                minDamage: 21,
                maxDamage: 29,
            },
            {
                worldLevel: 10,
                minHp: 290,
                maxHp: 330,
                minDamage: 23,
                maxDamage: 30,
            },
            {
                worldLevel: 11,
                minHp: 320,
                maxHp: 360,
                minDamage: 25,
                maxDamage: 32,
            },
            {
                worldLevel: 12,
                minHp: 365,
                maxHp: 415,
                minDamage: 28,
                maxDamage: 35,
            },
            {
                worldLevel: 13,
                minHp: 415,
                maxHp: 470,
                minDamage: 31,
                maxDamage: 38,
            },
            {
                worldLevel: 14,
                minHp: 470,
                maxHp: 525,
                minDamage: 33,
                maxDamage: 40,
            },
            {
                worldLevel: 15,
                minHp: 525,
                maxHp: 580,
                minDamage: 36,
                maxDamage: 44,
            },
            {
                worldLevel: 16,
                minHp: 580,
                maxHp: 645,
                minDamage: 42,
                maxDamage: 54,
            },
            {
                worldLevel: 17,
                minHp: 645,
                maxHp: 710,
                minDamage: 54,
                maxDamage: 65,
            },
            {
                worldLevel: 18,
                minHp: 710,
                maxHp: 775,
                minDamage: 65,
                maxDamage: 78,
            },
            {
                worldLevel: 19,
                minHp: 775,
                maxHp: 840,
                minDamage: 80,
                maxDamage: 105,
            },
            {
                worldLevel: 20,
                minHp: 880,
                maxHp: 1100,
                minDamage: 90,
                maxDamage: 125,
            },
            {
                worldLevel: 21,
                minHp: 950,
                maxHp: 1150,
                minDamage: 95,
                maxDamage: 130,
            },
            {
                worldLevel: 22,
                minHp: 1020,
                maxHp: 1225,
                minDamage: 100,
                maxDamage: 135,
            },
            {
                worldLevel: 23,
                minHp: 1100,
                maxHp: 1300,
                minDamage: 105,
                maxDamage: 140,
            },
            {
                worldLevel: 24,
                minHp: 1180,
                maxHp: 1375,
                minDamage: 110,
                maxDamage: 145,
            },
            {
                worldLevel: 25,
                minHp: 1260,
                maxHp: 1450,
                minDamage: 115,
                maxDamage: 150,
            },
        ];

        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
