export default {
    name: "Fatui Pyro Agent",
    group: "Fatui",
    hpConstant: 5,
    atkConstant: 4,
    baseHp: 450,
    baseAtk: 80,
    minExp: 10,
    maxExp: 25,
    minWorldLevel: 13,
    image: "https://lh.elara.workers.dev/rpg/monsters/fatui_pyro_agent.png",
    drops: [
        {
            item: "Hunter's Sacrificial Knife",
            minAmount: 1,
            maxAmount: 2,
            chance: 75,
        },
        {
            item: "Agent's Sacrificial Knife",
            minAmount: 1,
            maxAmount: 2,
            chance: 25,
        },
    ],
    locations: [
        "Qingxu Pool",
        "Lingju Pass",
        "Lumberpick Valley",
        "Dunyu Ruins",
        "Nantianmen",
        "Tianqiu Valley",
        "Luhua Pool",
        "Guili Plains",
        "Jueyun Karst",
    ],

    critChance: 50,
    critValue: 2,
    defChance: 90,
    defValue: 100,
};
