export default {
    name: "Fathomless Flames",
    group: "Abyss",
    minHp: 700,
    maxHp: 1100,
    minDamage: 140,
    maxDamage: 180,
    minExp: 15,
    maxExp: 30,
    minWorldLevel: 17,
    image: "https://lh.elara.workers.dev/rpg/monsters/fathomless_flame.png",
    drops: [
        {
            item: "Dead Ley Line Branch",
            minAmount: 1,
            maxAmount: 2,
            chance: 75,
        },
        {
            item: "Dead Ley Line Leaves",
            minAmount: 1,
            maxAmount: 2,
            chance: 25,
        },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],
    locations: [
        "Qingxu Pool",
        "Lingju Pass",
        "Lumberpick Valley",
        "Dunyu Ruins",
        "Nantianmen",
        "Tianqiu Valley",
        "Luhua Pool",
        "Guili Plains",
        "Jueyun Karst",
    ],
    critChance: 75,
    critValue: 2.5,
    defChance: 60,
    defValue: 50,
};
