export default {
    name: "Frost Fall",
    group: "Abyss",
    hpConstant: 5,
    atkConstant: 4,
    baseHp: 750,
    baseAtk: 150,
    minExp: 12,
    maxExp: 28,
    minWorldLevel: 16,
    image: "https://lh.elara.workers.dev/rpg/monsters/frost_fall.png",
    drops: [
        {
            item: "Dead Ley Line Branch",
            minAmount: 1,
            maxAmount: 2,
            chance: 75,
        },
        {
            item: "Dead Ley Line Leaves",
            minAmount: 1,
            maxAmount: 2,
            chance: 25,
        },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],
    locations: [
        "Qingxu Pool",
        "Lingju Pass",
        "Lumberpick Valley",
        "Dunyu Ruins",
        "Nantianmen",
        "Tianqiu Valley",
        "Luhua Pool",
        "Guili Plains",
        "Jueyun Karst",
    ],
    critChance: 20,
    critValue: 1.5,
    defChance: 95,
    defValue: 120,
};
