export default {
    name: "Nobushi: Jintouban",
    group: "Human",
    minHp: 800,
    maxHp: 100,
    minDamage: 50,
    maxDamage: 50,
    minExp: 10,
    maxExp: 20,
    minWorldLevel: 16,
    image: "https://lh.elara.workers.dev/rpg/monsters/jintouban.png",
    critChance: 25,
    critValue: 5,
    defChance: 10,
    defValue: 5,
    drops: [
        {
            item: "Silver Hoarder Insignia",
            minAmount: 1,
            maxAmount: 2,
            chance: 100,
        },
        {
            item: "Golden Raven Insignia",
            minAmount: 1,
            maxAmount: 1,
            chance: 50,
        },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],
    locations: [
        "Qingxu Pool",
        "Lingju Pass",
        "Lumberpick Valley",
        "Dunyu Ruins",
        "Nantianmen",
        "Tianqiu Valley",
        "Luhua Pool",
        "Guili Plains",
        "Jueyun Karst",
    ],
};
