export default {
    name: "Treasure Hoarder Potioneer",
    group: "Human",
    minHp: 150,
    maxHp: 250,
    minDamage: 25,
    maxDamage: 50,
    minExp: 7,
    maxExp: 13,
    minWorldLevel: 8,
    image: "https://lh.elara.workers.dev/rpg/monsters/treasure_hoarder_potioneer.png",
    critChance: 10,
    critValue: 3,
    defChance: 50,
    defValue: 0.5,
    drops: [
        {
            item: "Silver Raven Insignia",
            minAmount: 1,
            maxAmount: 3,
            chance: 100,
        },
        {
            item: "Golden Raven Insignia",
            minAmount: 1,
            maxAmount: 2,
            chance: 50,
        },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],
    locations: [
        "Nantianmen",
        "Luhua Pool",
        "Dunyu Ruins",
        "Jueyun Karst",
        "Lumberpick Valley",
    ],
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            {
                worldLevel: 8,
                minHp: 312,
                maxHp: 402,
                minDamage: 18,
                maxDamage: 26,
            },
            {
                worldLevel: 9,
                minHp: 402,
                maxHp: 465,
                minDamage: 21,
                maxDamage: 29,
            },
            {
                worldLevel: 10,
                minHp: 465,
                maxHp: 525,
                minDamage: 23,
                maxDamage: 30,
            },
            {
                worldLevel: 11,
                minHp: 510,
                maxHp: 570,
                minDamage: 25,
                maxDamage: 32,
            },
            {
                worldLevel: 12,
                minHp: 578,
                maxHp: 653,
                minDamage: 28,
                maxDamage: 35,
            },
            {
                worldLevel: 13,
                minHp: 652,
                maxHp: 735,
                minDamage: 31,
                maxDamage: 38,
            },
            {
                worldLevel: 14,
                minHp: 735,
                maxHp: 818,
                minDamage: 33,
                maxDamage: 40,
            },
            {
                worldLevel: 15,
                minHp: 818,
                maxHp: 900,
                minDamage: 36,
                maxDamage: 44,
            },
            {
                worldLevel: 16,
                minHp: 900,
                maxHp: 998,
                minDamage: 42,
                maxDamage: 54,
            },
            {
                worldLevel: 17,
                minHp: 998,
                maxHp: 1095,
                minDamage: 54,
                maxDamage: 65,
            },
            {
                worldLevel: 18,
                minHp: 1095,
                maxHp: 1193,
                minDamage: 65,
                maxDamage: 78,
            },
            {
                worldLevel: 19,
                minHp: 1193,
                maxHp: 1290,
                minDamage: 80,
                maxDamage: 105,
            },
            {
                worldLevel: 20,
                minHp: 1350,
                maxHp: 1680,
                minDamage: 90,
                maxDamage: 125,
            },
        ];
        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
