export default {
    name: "Mirror Maiden",
    group: "Fatui",
    minHp: 0,
    maxHp: 0,
    minDamage: 0,
    maxDamage: 0,
    minExp: 10,
    maxExp: 15,
    minWorldLevel: 11,
    image: "https://lh.elara.workers.dev/rpg/monsters/mirror_maiden.png",
    drops: [
        { item: "Dismal Prism", minAmount: 1, maxAmount: 2, chance: 75 },
        { item: "Crystal Prism", minAmount: 1, maxAmount: 2, chance: 25 },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],
    locations: [
        "Qingxu Pool",
        "Lingju Pass",
        "Lumberpick Valley",
        "Dunyu Ruins",
        "Nantianmen",
        "Tianqiu Valley",
        "Luhua Pool",
        "Guili Plains",
        "Jueyun Karst",
    ],

    critChance: 0,
    critValue: 0,
    defChance: 0,
    defValue: 0,
};
