import { MonsterGroup } from "./helpers/monsterHelper";

export const locationGroupWeights: {
    [location: string]: { [group in MonsterGroup]?: number };
} = {
    "Liyue Harbor": {
        [MonsterGroup.Slime]: 3,
        [MonsterGroup.Hilichurl]: 3,
        [MonsterGroup.Abyss]: 1,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 1,
        [MonsterGroup.Machine]: 1,
        [MonsterGroup.Eremite]: 1,
        [MonsterGroup.Nobushi]: 1,
        [MonsterGroup.Specter]: 4,
        [MonsterGroup.Beast]: 3,
        [MonsterGroup.Wayob]: 2,
    },
    "Qingxu Pool": {
        [MonsterGroup.Slime]: 4,
        [MonsterGroup.Hilichurl]: 2,
        [MonsterGroup.Abyss]: 2,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 1,
        [MonsterGroup.Machine]: 3,
        [MonsterGroup.Eremite]: 1,
        [MonsterGroup.Nobushi]: 1,
        [MonsterGroup.Specter]: 2,
        [MonsterGroup.Beast]: 3,
        [MonsterGroup.Wayob]: 2,
    },
    "Lingju Pass": {
        [MonsterGroup.Slime]: 2,
        [MonsterGroup.Hilichurl]: 2,
        [MonsterGroup.Abyss]: 2,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 2,
        [MonsterGroup.Machine]: 2,
        [MonsterGroup.Eremite]: 5,
        [MonsterGroup.Nobushi]: 1,
        [MonsterGroup.Specter]: 4,
        [MonsterGroup.Beast]: 3,
        [MonsterGroup.Wayob]: 2,
    },
    "Lumberpick Valley": {
        [MonsterGroup.Slime]: 3,
        [MonsterGroup.Hilichurl]: 5,
        [MonsterGroup.Abyss]: 1,
        [MonsterGroup.Human]: 2,
        [MonsterGroup.Fatui]: 1,
        [MonsterGroup.Machine]: 2,
        [MonsterGroup.Eremite]: 3,
        [MonsterGroup.Nobushi]: 1,
        [MonsterGroup.Specter]: 2,
        [MonsterGroup.Beast]: 3,
        [MonsterGroup.Wayob]: 2,
    },
    "Dunyu Ruins": {
        [MonsterGroup.Slime]: 2,
        [MonsterGroup.Hilichurl]: 2,
        [MonsterGroup.Abyss]: 3,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 3,
        [MonsterGroup.Machine]: 2,
        [MonsterGroup.Eremite]: 4,
        [MonsterGroup.Nobushi]: 1,
        [MonsterGroup.Specter]: 2,
        [MonsterGroup.Beast]: 3,
        [MonsterGroup.Wayob]: 2,
    },
    Nantianmen: {
        [MonsterGroup.Slime]: 1,
        [MonsterGroup.Hilichurl]: 1,
        [MonsterGroup.Abyss]: 1,
        [MonsterGroup.Human]: 5,
        [MonsterGroup.Fatui]: 2,
        [MonsterGroup.Machine]: 2,
        [MonsterGroup.Eremite]: 1,
        [MonsterGroup.Nobushi]: 4,
        [MonsterGroup.Specter]: 1,
        [MonsterGroup.Beast]: 3,
        [MonsterGroup.Wayob]: 2,
    },
    "Tianqiu Valley": {
        [MonsterGroup.Slime]: 1,
        [MonsterGroup.Hilichurl]: 3,
        [MonsterGroup.Abyss]: 1,
        [MonsterGroup.Human]: 2,
        [MonsterGroup.Fatui]: 4,
        [MonsterGroup.Machine]: 2,
        [MonsterGroup.Eremite]: 1,
        [MonsterGroup.Nobushi]: 1,
        [MonsterGroup.Specter]: 5,
        [MonsterGroup.Beast]: 3,
        [MonsterGroup.Wayob]: 2,
    },
    "Luhua Pool": {
        [MonsterGroup.Slime]: 4,
        [MonsterGroup.Hilichurl]: 1,
        [MonsterGroup.Abyss]: 1,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 1,
        [MonsterGroup.Machine]: 2,
        [MonsterGroup.Eremite]: 1,
        [MonsterGroup.Nobushi]: 3,
        [MonsterGroup.Specter]: 2,
        [MonsterGroup.Beast]: 3,
        [MonsterGroup.Wayob]: 2,
    },
    "Guili Plains": {
        [MonsterGroup.Slime]: 3,
        [MonsterGroup.Hilichurl]: 3,
        [MonsterGroup.Abyss]: 2,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 2,
        [MonsterGroup.Machine]: 4,
        [MonsterGroup.Eremite]: 1,
        [MonsterGroup.Nobushi]: 1,
        [MonsterGroup.Specter]: 1,
        [MonsterGroup.Beast]: 3,
        [MonsterGroup.Wayob]: 2,
    },
    "Jueyun Karst": {
        [MonsterGroup.Slime]: 2,
        [MonsterGroup.Hilichurl]: 1,
        [MonsterGroup.Abyss]: 4,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 1,
        [MonsterGroup.Machine]: 3,
        [MonsterGroup.Eremite]: 1,
        [MonsterGroup.Nobushi]: 2,
        [MonsterGroup.Specter]: 1,
        [MonsterGroup.Beast]: 3,
        [MonsterGroup.Wayob]: 2,
    },
    Default: {
        [MonsterGroup.Slime]: 2,
        [MonsterGroup.Hilichurl]: 2,
        [MonsterGroup.Abyss]: 2,
        [MonsterGroup.Human]: 2,
        [MonsterGroup.Fatui]: 2,
        [MonsterGroup.Machine]: 2,
        [MonsterGroup.Eremite]: 2,
        [MonsterGroup.Nobushi]: 2,
        [MonsterGroup.Specter]: 2,
        [MonsterGroup.Beast]: 2,
        [MonsterGroup.Wayob]: 2,
    },
};
