import { MonsterGroup } from "./groups";

export const locationGroupWeights: {
    [location: string]: { [group in MonsterGroup]?: number };
} = {
    "Liyue Harbor": {
        [MonsterGroup.Slime]: 3,
        [MonsterGroup.Hilichurl]: 3,
        [MonsterGroup.Abyss]: 1,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 1,
        [MonsterGroup.Machine]: 1,
    },
    "Qingxu Pool": {
        [MonsterGroup.Slime]: 4,
        [MonsterGroup.Hilichurl]: 2,
        [MonsterGroup.Abyss]: 2,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 1,
        [MonsterGroup.Machine]: 3,
    },
    "Lingju Pass": {
        [MonsterGroup.Slime]: 2,
        [MonsterGroup.Hilichurl]: 4,
        [MonsterGroup.Abyss]: 2,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 2,
        [MonsterGroup.Machine]: 1,
    },
    "Lumberpick Valley": {
        [MonsterGroup.Slime]: 3,
        [MonsterGroup.Hilichurl]: 5,
        [MonsterGroup.Abyss]: 1,
        [MonsterGroup.Human]: 2,
        [MonsterGroup.Fatui]: 1,
        [MonsterGroup.Machine]: 1,
    },
    "Dunyu Ruins": {
        [MonsterGroup.Slime]: 2,
        [MonsterGroup.Hilichurl]: 2,
        [MonsterGroup.Abyss]: 4,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 3,
        [MonsterGroup.Machine]: 1,
    },
    Nantianmen: {
        [MonsterGroup.Slime]: 1,
        [MonsterGroup.Hilichurl]: 1,
        [MonsterGroup.Abyss]: 1,
        [MonsterGroup.Human]: 5,
        [MonsterGroup.Fatui]: 2,
        [MonsterGroup.Machine]: 1,
    },
    "Tianqiu Valley": {
        [MonsterGroup.Slime]: 1,
        [MonsterGroup.Hilichurl]: 3,
        [MonsterGroup.Abyss]: 2,
        [MonsterGroup.Human]: 2,
        [MonsterGroup.Fatui]: 4,
        [MonsterGroup.Machine]: 1,
    },
    "Luhua Pool": {
        [MonsterGroup.Slime]: 4,
        [MonsterGroup.Hilichurl]: 1,
        [MonsterGroup.Abyss]: 1,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 1,
        [MonsterGroup.Machine]: 1,
    },
    "Guili Plains": {
        [MonsterGroup.Slime]: 3,
        [MonsterGroup.Hilichurl]: 3,
        [MonsterGroup.Abyss]: 2,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 2,
        [MonsterGroup.Machine]: 4,
    },
    "Jueyun Karst": {
        [MonsterGroup.Slime]: 2,
        [MonsterGroup.Hilichurl]: 1,
        [MonsterGroup.Abyss]: 4,
        [MonsterGroup.Human]: 1,
        [MonsterGroup.Fatui]: 1,
        [MonsterGroup.Machine]: 3,
    },
    Default: {
        [MonsterGroup.Slime]: 2,
        [MonsterGroup.Hilichurl]: 2,
        [MonsterGroup.Abyss]: 2,
        [MonsterGroup.Human]: 2,
        [MonsterGroup.Fatui]: 2,
        [MonsterGroup.Machine]: 2,
    },
};
