import { texts, customEmoji } from "./index";

const r = `${customEmoji.a.z_coins} \`%AMOUNT% ${texts.c.u}\``;

export const battleMessages: string[] = [
  `You went out hunting for Hilichurls and earned ${r}.`,
  `Killing Anemo Slimes for no reason gave you ${r}.`,
  `Jean gave you ${r} as payment for being a Knight of Favonius.`,
  `The blacksmith paid you ${r} for your Iron Chunks.`,
  `You sold Fisherman's Toast to Amber and got paid ${r}.`,
  `You went around picking Dandelions as a side job, and earned ${r}.`,
  `You completed a mission, and killed a nearby Ruin Guard for ${r}.`,
  `After defeating the Electro Hypostasis, you claimed ${r} worth of treasures.`,
  `Xiangling paid you ${r} for helping her gather rare ingredients.`,
  `By selling your surplus of Sweet Flowers, you earned ${r}.`,
  `You escorted a transport balloon safely and received ${r} for your trouble.`,
  `You helped Timmie with his pigeons, surprisingly you got ${r}.`,
  `You traded some valuable artifacts to Zhongli and received ${r}.`,
  `Your win against a group of Treasure Hoarders netted you ${r}.`,
  `The Adventurers' Guild compensated you with ${r} for reporting your findings.`,
  `For your performance in the Spiral Abyss, you were awarded ${r}.`,
  `You found a hidden chest in the mountains and sold the contents for ${r}.`,
  `You helped Mona with her astrological research and got ${r} as a token of gratitude.`,
  `By completing a Ley Line Outcrop challenge, you secured ${r}.`,
  `You bartered some Cor Lapis with a merchant in Liyue for ${r}.`,
  `Your sharp eye spotted some rare Crystal Cores, selling them earned you ${r}.`,
  `For your tales of heroism, the local bard composed a song and you were tipped ${r}.`,
  `The Qixing rewarded you with ${r} for your aid during a crisis in Liyue.`,
  `Abyss Mage bounty completed. You collected the reward of ${r}.`,
  `After a performance in the Dawn Winery, Diluc slipped you ${r}.`,
  `Soothing the wrath of a Stormterror Dvalin, you found ${r} amidst the ruins.`,
  `Kaeya challenged you to a duel of wits and lost, handing over ${r}.`,
  `Discovering a new waypoint awarded you ${r} from the Adventurers' Guild.`,
  `Liyue Harbor's Commerce Guild paid you ${r} for escorting their cargo.`,
  `After winning the Windtrace event, you received ${r} as a prize.`,
  `Defeating the Geo Hypostasis, you extracted ${r} worth of Geo Sigils.`,
  `Ningguang gave you ${r} for delivering a message to the Adepti.`,
  `Selling some of your gliding champion medals to Cyrus earned you ${r}.`,
  `Venti's impromptu poetry contest in the plaza earned you ${r} from the crowd.`,
  `Finding a rare chest in Stormterror's Lair, you sold the contents for ${r}.`,
  `A successful commission to clear out the Spiral Abyss Corridor granted you ${r}.`,
  `Childe paid you ${r} for information on the Fatui's movements.`,
  `The Wangsheng Funeral Parlor rewarded your discretion with ${r}.`,
  `Helping Sayu with her ninja training, she handed you ${r} as thanks.`,
  `By taming a wild boar, you earned ${r} from the Springvale hunters.`,
  `A grateful Sumeru scholar paid you ${r} for retrieving lost research notes.`,
  `Klee's treasure hunting game led you to a stash with ${r} inside.`,
  `Helping Albedo with his alchemical experiments netted you ${r}.`,
  `A smooth negotiation with the Treasure Hoarders saw you walk away ${r} richer.`,
  `Yanfei required legal assistance and compensated you ${r} for your counsel.`,
  `Thoma needed help with housekeeping duties and paid you ${r} for your time.`,
  `Ganyu thanked you for your help with Qixing paperwork with a gift of ${r}.`,
  `By deciphering ancient texts in the library, Lisa rewarded your efforts with ${r}.`,
  `Successfully guiding a group of adventurers through Dragonspine, you were thanked with ${r}.`,
  `You harvested a bumper crop of Qingxin flowers, and Baizhu paid you ${r} for them.`,
  `For capturing stunning views of Teyvat with your camera, the Yae Publishing House paid you ${r}.`,
  `You cleared the snow off the paths in Mondstadt and were tipped ${r} by grateful citizens.`,
  `Hutao entrusted you with a special task and gifted you ${r} for your discretion and efficiency.`,
  `You crafted a new batch of potions for Sucrose's experiments, earning you ${r}.`,
  `After performing maintenance on the Ballista in Qingce Village, you received ${r}.`,
  `Catching a rare Golden Crab, you sold it to Beidou's crew for a hefty sum of ${r}.`,
  `You helped Noelle in her Knightly training, and she managed to scrape together ${r} for you.`,
  `Your assistance in expelling the evil spirits from Wangshu Inn was rewarded with ${r}.`,
  `After sharing tales of your travels at Angel's Share, the patrons chipped in to give you ${r}.`,
  `You repaired a damaged section of the Great Wall in Liyue, earning a reward of ${r} from the Millelith.`,
  `Earning praise for your cooking skills at Xinyue Kiosk, Chef Mao gave you a bonus of ${r}.`,
  `By organizing the library books in Favonius Headquarters, you were handed ${r} for your meticulous work.`,
  `Diona served you a special drink on the house, and you received ${r} in tips from impressed customers.`,
  `Razor asked for help in tracking a pack of wolves, and you were given ${r} for your assistance.`,
  `In return for teaching new recruits about gliding, Amber paid you ${r}.`,
  `Your skills in calming down a startled Seelie impressed a traveler, who gave you ${r}.`,
  `For your dedication in feeding and caring for the birds in Mondstadt, Timmie gave you his savings of ${r}.`,
  `You crafted an exquisite jewelry piece for the Mingxing Jewelry store and were compensated ${r}.`,
  `By providing transport services with your Waverider, you earned ${r} from various travelers.`,
  `You lent your voice for the choir in the Mondstadt cathedral and received a donation of ${r}.`,
  `Creating a custom constellation map for a client, Mona proudly paid you ${r} for your collaboration.`,
  `Rosaria needed help patrolling at night and offered ${r} for your company and vigilance.`,
  `Fischl's literary work became a hit, and as a co-author, you were awarded ${r}.`,
  `After gathering rare specimens for Tsaritsa's collection, you were discreetly handed ${r}.`,
  `Your help with deciphering the ancient stone tablets in Sal Terrae earned you a scholar's reward of ${r}.`,
  `You provided some melodic tunes for the bard Venti, who in turn collected ${r} for you from the crowd.`,
  `A successful harvest of Starconches along the beach was bought by a collector for ${r}.`,
  `By joining Kujou Sara in her training exercises, you were compensated with ${r} for your endurance and skill.`,
  `Lending your expertise to help manage the Wansheng Funeral Parlor's books, you were quietly given ${r}.`,
  `You modeled for a new line of adventurer's gear and were paid ${r} for your image rights.`,
  `Completing a challenging mountain climb, you planted a flag and were sponsored ${r} by the Adventurers' Guild.`,
  `Assisting a group of researchers in the Dihua Marsh, they were pleased to pay you ${r} for your protection and help.`,
  `A successful ghost hunt with Hu Tao surprised you with a bonus of ${r} for your bravery.`,
  `You solved a mysterious puzzle in the Golden House, earning a finder's fee of ${r}.`,
  `After a dazzling performance at the Lantern Rite Festival, Ningguang presented you with ${r}.`,
  `You collected and delivered a bouquet of Cecilia flowers to the Dawn Winery for a special event, earning ${r}.`,
];
