import { MonsterGroup } from "../../groups";

export default {
    currentHp: 0,
    name: "Cryo Slime",
    group: MonsterGroup.Slime,
    minExp: 3,
    maxExp: 6,
    minWorldLevel: 1,
    image: "https://lh.elara.workers.dev/rpg/monsters/cryo_slime.png",
    drops: [
        {
            item: "Slime Condensate",
            minAmount: 1,
            maxAmount: 2,
            chance: 90,
        },
        {
            item: "Slime Secretions",
            minAmount: 1,
            maxAmount: 2,
            chance: 50,
        },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            { worldLevel: 1, minHp: 12, maxHp: 16, minDamage: 2, maxDamage: 3 },
            { worldLevel: 2, minHp: 18, maxHp: 27, minDamage: 3, maxDamage: 4 },
            { worldLevel: 3, minHp: 29, maxHp: 38, minDamage: 4, maxDamage: 7 },
            {
                worldLevel: 4,
                minHp: 40,
                maxHp: 54,
                minDamage: 5,
                maxDamage: 10,
            },
            {
                worldLevel: 5,
                minHp: 57,
                maxHp: 75,
                minDamage: 7,
                maxDamage: 11,
            },
            {
                worldLevel: 6,
                minHp: 80,
                maxHp: 105,
                minDamage: 8,
                maxDamage: 13,
            },
            {
                worldLevel: 7,
                minHp: 112,
                maxHp: 135,
                minDamage: 9,
                maxDamage: 14,
            },
            {
                worldLevel: 8,
                minHp: 142,
                maxHp: 161,
                minDamage: 12,
                maxDamage: 18,
            },
            {
                worldLevel: 9,
                minHp: 162,
                maxHp: 190,
                minDamage: 13,
                maxDamage: 20,
            },
            {
                worldLevel: 10,
                minHp: 192,
                maxHp: 217,
                minDamage: 14,
                maxDamage: 21,
            },
            {
                worldLevel: 11,
                minHp: 217,
                maxHp: 270,
                minDamage: 16,
                maxDamage: 22,
            },
            {
                worldLevel: 12,
                minHp: 265,
                maxHp: 325,
                minDamage: 19,
                maxDamage: 25,
            },
            {
                worldLevel: 13,
                minHp: 318,
                maxHp: 375,
                minDamage: 22,
                maxDamage: 28,
            },
            {
                worldLevel: 14,
                minHp: 378,
                maxHp: 432,
                minDamage: 24,
                maxDamage: 32,
            },
            {
                worldLevel: 15,
                minHp: 450,
                maxHp: 492,
                minDamage: 28,
                maxDamage: 37,
            },
            {
                worldLevel: 16,
                minHp: 570,
                maxHp: 595,
                minDamage: 39,
                maxDamage: 52,
            },
            {
                worldLevel: 17,
                minHp: 594,
                maxHp: 652,
                minDamage: 48,
                maxDamage: 63,
            },
            {
                worldLevel: 18,
                minHp: 655,
                maxHp: 720,
                minDamage: 62,
                maxDamage: 72,
            },
            {
                worldLevel: 19,
                minHp: 739,
                maxHp: 765,
                minDamage: 73,
                maxDamage: 98,
            },
            {
                worldLevel: 20,
                minHp: 873,
                maxHp: 1150,
                minDamage: 85,
                maxDamage: 117,
            },
        ];
        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
