import { MonsterGroup } from "../../groups";

export default {
    currentHp: 0,
    name: "Dendro Slime",
    group: MonsterGroup.Slime,
    minExp: 5,
    maxExp: 10,
    minWorldLevel: 4,
    image: "https://lh.elara.workers.dev/rpg/monsters/dendro_slime.png",
    drops: [
        {
            item: "Slime Secretions",
            minAmount: 1,
            maxAmount: 3,
            chance: 90,
        },
        {
            item: "Slime Concentrate",
            minAmount: 1,
            maxAmount: 2,
            chance: 75,
        },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],

    critChance: 10,
    critValue: 1.5,
    defChance: 20,
    defValue: 0.2,
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            {
                worldLevel: 4,
                minHp: 39,
                maxHp: 55,
                minDamage: 6,
                maxDamage: 10,
            },
            {
                worldLevel: 5,
                minHp: 55,
                maxHp: 77,
                minDamage: 7,
                maxDamage: 12,
            },
            {
                worldLevel: 6,
                minHp: 77,
                maxHp: 110,
                minDamage: 8,
                maxDamage: 14,
            },
            {
                worldLevel: 7,
                minHp: 110,
                maxHp: 138,
                minDamage: 10,
                maxDamage: 15,
            },
            {
                worldLevel: 8,
                minHp: 138,
                maxHp: 165,
                minDamage: 12,
                maxDamage: 17,
            },
            {
                worldLevel: 9,
                minHp: 165,
                maxHp: 193,
                minDamage: 14,
                maxDamage: 19,
            },
            {
                worldLevel: 10,
                minHp: 193,
                maxHp: 220,
                minDamage: 15,
                maxDamage: 20,
            },
            {
                worldLevel: 11,
                minHp: 220,
                maxHp: 275,
                minDamage: 17,
                maxDamage: 23,
            },
            {
                worldLevel: 12,
                minHp: 275,
                maxHp: 330,
                minDamage: 20,
                maxDamage: 25,
            },
            {
                worldLevel: 13,
                minHp: 330,
                maxHp: 385,
                minDamage: 23,
                maxDamage: 27,
            },
            {
                worldLevel: 14,
                minHp: 385,
                maxHp: 440,
                minDamage: 25,
                maxDamage: 30,
            },
            {
                worldLevel: 15,
                minHp: 440,
                maxHp: 495,
                minDamage: 27,
                maxDamage: 35,
            },
            {
                worldLevel: 16,
                minHp: 550,
                maxHp: 605,
                minDamage: 40,
                maxDamage: 50,
            },
            {
                worldLevel: 17,
                minHp: 605,
                maxHp: 660,
                minDamage: 50,
                maxDamage: 60,
            },
            {
                worldLevel: 18,
                minHp: 660,
                maxHp: 715,
                minDamage: 60,
                maxDamage: 75,
            },
            {
                worldLevel: 19,
                minHp: 715,
                maxHp: 770,
                minDamage: 75,
                maxDamage: 100,
            },
            {
                worldLevel: 20,
                minHp: 880,
                maxHp: 1100,
                minDamage: 80,
                maxDamage: 120,
            },
        ];
        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
