export default {
    currentHp: 0,
    name: "Large Cryo Slime",
    group: "Slime",
    minExp: 5,
    maxExp: 10,
    minWorldLevel: 4,
    image: "https://lh.elara.workers.dev/rpg/monsters/large_cryo_slime.png",
    drops: [
        {
            item: "Slime Secretions",
            minAmount: 2,
            maxAmount: 4,
            chance: 100,
        },
        {
            item: "Slime Concentrate",
            minAmount: 1,
            maxAmount: 1,
            chance: 50,
        },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],
    locations: [
        "Qingxu Pool",
        "Lingju Pass",
        "Lumberpick Valley",
        "Dunyu Ruins",
        "Nantianmen",
        "Tianqiu Valley",
        "Luhua Pool",
        "Guili Plains",
        "Jueyun Karst",
    ],

    critChance: 10,
    critValue: 1.5,
    defChance: 20,
    defValue: 0.2,
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            {
                worldLevel: 4,
                minHp: 49,
                maxHp: 65,
                minDamage: 6,
                maxDamage: 10,
            },
            {
                worldLevel: 5,
                minHp: 65,
                maxHp: 87,
                minDamage: 7,
                maxDamage: 12,
            },
            {
                worldLevel: 6,
                minHp: 87,
                maxHp: 120,
                minDamage: 8,
                maxDamage: 14,
            },
            {
                worldLevel: 7,
                minHp: 120,
                maxHp: 148,
                minDamage: 10,
                maxDamage: 15,
            },
            {
                worldLevel: 8,
                minHp: 148,
                maxHp: 175,
                minDamage: 12,
                maxDamage: 17,
            },
            {
                worldLevel: 9,
                minHp: 175,
                maxHp: 203,
                minDamage: 14,
                maxDamage: 19,
            },
            {
                worldLevel: 10,
                minHp: 203,
                maxHp: 230,
                minDamage: 15,
                maxDamage: 20,
            },
            {
                worldLevel: 11,
                minHp: 230,
                maxHp: 285,
                minDamage: 17,
                maxDamage: 23,
            },
            {
                worldLevel: 12,
                minHp: 285,
                maxHp: 340,
                minDamage: 20,
                maxDamage: 25,
            },
            {
                worldLevel: 13,
                minHp: 340,
                maxHp: 395,
                minDamage: 23,
                maxDamage: 27,
            },
            {
                worldLevel: 14,
                minHp: 395,
                maxHp: 450,
                minDamage: 25,
                maxDamage: 30,
            },
            {
                worldLevel: 15,
                minHp: 450,
                maxHp: 505,
                minDamage: 27,
                maxDamage: 35,
            },
            {
                worldLevel: 16,
                minHp: 560,
                maxHp: 615,
                minDamage: 40,
                maxDamage: 50,
            },
            {
                worldLevel: 17,
                minHp: 615,
                maxHp: 670,
                minDamage: 50,
                maxDamage: 60,
            },
            {
                worldLevel: 18,
                minHp: 670,
                maxHp: 725,
                minDamage: 60,
                maxDamage: 75,
            },
            {
                worldLevel: 19,
                minHp: 725,
                maxHp: 780,
                minDamage: 75,
                maxDamage: 100,
            },
            {
                worldLevel: 20,
                minHp: 890,
                maxHp: 1110,
                minDamage: 80,
                maxDamage: 120,
            },
        ];
        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
