import { MonsterGroup } from "../../monsterHelper";

export default {
    currentHp: 0,
    name: "Large Cryo Slime",
    group: MonsterGroup.Slime,
    minExp: 5,
    maxExp: 10,
    minWorldLevel: 4,
    image: "https://lh.elara.workers.dev/rpg/monsters/large_cryo_slime.png",
    drops: [
        {
            item: "Slime Secretions",
            minAmount: 2,
            maxAmount: 4,
            chance: 90,
        },
        {
            item: "Slime Concentrate",
            minAmount: 1,
            maxAmount: 1,
            chance: 50,
        },
        {
            item: "Life Essence",
            minAmount: 1,
            maxAmount: 1,
            chance: 10,
        },
    ],

    critChance: 10,
    critValue: 1.5,
    defChance: 20,
    defValue: 0.2,
    getStatsForWorldLevel(worldLevel: number) {
        const stats = [
            {
                worldLevel: 4,
                minHp: 49,
                maxHp: 65,
                minDamage: 6,
                maxDamage: 10,
            },
            {
                worldLevel: 5,
                minHp: 65,
                maxHp: 87,
                minDamage: 7,
                maxDamage: 12,
            },
            {
                worldLevel: 6,
                minHp: 87,
                maxHp: 120,
                minDamage: 8,
                maxDamage: 14,
            },
            {
                worldLevel: 7,
                minHp: 120,
                maxHp: 148,
                minDamage: 10,
                maxDamage: 15,
            },
            {
                worldLevel: 8,
                minHp: 148,
                maxHp: 175,
                minDamage: 12,
                maxDamage: 17,
            },
            {
                worldLevel: 9,
                minHp: 175,
                maxHp: 203,
                minDamage: 14,
                maxDamage: 19,
            },
            {
                worldLevel: 10,
                minHp: 203,
                maxHp: 230,
                minDamage: 15,
                maxDamage: 20,
            },
            {
                worldLevel: 11,
                minHp: 230,
                maxHp: 285,
                minDamage: 17,
                maxDamage: 23,
            },
            {
                worldLevel: 12,
                minHp: 285,
                maxHp: 340,
                minDamage: 20,
                maxDamage: 25,
            },
            {
                worldLevel: 13,
                minHp: 340,
                maxHp: 395,
                minDamage: 23,
                maxDamage: 27,
            },
            {
                worldLevel: 14,
                minHp: 395,
                maxHp: 450,
                minDamage: 25,
                maxDamage: 30,
            },
            {
                worldLevel: 15,
                minHp: 450,
                maxHp: 505,
                minDamage: 27,
                maxDamage: 35,
            },
            {
                worldLevel: 16,
                minHp: 560,
                maxHp: 615,
                minDamage: 40,
                maxDamage: 50,
            },
            {
                worldLevel: 17,
                minHp: 615,
                maxHp: 670,
                minDamage: 50,
                maxDamage: 60,
            },
            {
                worldLevel: 18,
                minHp: 670,
                maxHp: 725,
                minDamage: 60,
                maxDamage: 75,
            },
            {
                worldLevel: 19,
                minHp: 725,
                maxHp: 780,
                minDamage: 75,
                maxDamage: 100,
            },
            {
                worldLevel: 20,
                minHp: 890,
                maxHp: 1110,
                minDamage: 80,
                maxDamage: 120,
            },
            {
                worldLevel: 21,
                minHp: 900,
                maxHp: 1150,
                minDamage: 85,
                maxDamage: 125,
            },
            {
                worldLevel: 22,
                minHp: 950,
                maxHp: 1200,
                minDamage: 90,
                maxDamage: 130,
            },
            {
                worldLevel: 23,
                minHp: 1000,
                maxHp: 1250,
                minDamage: 95,
                maxDamage: 135,
            },
            {
                worldLevel: 24,
                minHp: 1050,
                maxHp: 1300,
                minDamage: 100,
                maxDamage: 140,
            },
            {
                worldLevel: 25,
                minHp: 1100,
                maxHp: 1350,
                minDamage: 105,
                maxDamage: 145,
            },
        ];
        return stats.find((stat) => stat.worldLevel === worldLevel) || null;
    },
};
