export const artifacts = {
    "Adventurer's Flower": {
        type: "Flower",
        sellPrice: 5,
        attackPower: 0,
        critChance: 0,
        critValue: 0,
        maxHP: 10,
        defChance: 0,
        defValue: 0,
        minWorldLevel: 2,
        chestChance: 15,
    },
    "Adventurer's Tail Feather": {
        type: "Plume",
        sellPrice: 5,
        attackPower: 1.5,
        critChance: 0,
        critValue: 0,
        maxHP: 0,
        defChance: 0,
        defValue: 0,
        minWorldLevel: 2,
        chestChance: 15,
    },
    "Adventurer's Pocket Watch": {
        type: "Sands",
        sellPrice: 5,
        attackPower: 1,
        critChance: 5,
        critValue: 0.25,
        maxHP: 5,
        defChance: 0,
        defValue: 0,
        minWorldLevel: 2,
        chestChance: 15,
    },
    "Adventurer's Golden Goblet": {
        type: "Goblet",
        sellPrice: 5,
        attackPower: 0,
        critChance: 0,
        critValue: 0.5,
        maxHP: 0,
        defChance: 10,
        defValue: 1.5,
        minWorldLevel: 2,
        chestChance: 15,
    },
    "Adventurer's Bandana": {
        type: "Circlet",
        sellPrice: 5,
        attackPower: 0,
        critChance: 15,
        critValue: 0,
        maxHP: 0,
        defChance: 0,
        defValue: 0,
        minWorldLevel: 2,
        chestChance: 15,
    },
    "Travelling Doctor's Silver Lotus": {
        type: "Flower",
        sellPrice: 6,
        attackPower: -2,
        critChance: 0,
        critValue: 0,
        maxHP: 15,
        defChance: 5,
        defValue: 8,
        minWorldLevel: 3,
        chestChance: 15,
    },
    "Travelling Doctor's Owl Feather": {
        type: "Plume",
        sellPrice: 6,
        attackPower: 2,
        critChance: 0,
        critValue: 0,
        maxHP: 0,
        defChance: 5,
        defValue: 4,
        minWorldLevel: 3,
        chestChance: 15,
    },
    "Travelling Doctor's Pocket Watch": {
        type: "Sands",
        sellPrice: 6,
        attackPower: 2,
        critChance: 3,
        critValue: 0.2,
        maxHP: 10,
        defChance: 5,
        defValue: 3,
        minWorldLevel: 3,
        chestChance: 15,
    },
    "Travelling Doctor's Medicine Pot": {
        type: "Goblet",
        sellPrice: 6,
        attackPower: 0,
        critChance: 0,
        critValue: 0.25,
        maxHP: 0,
        defChance: 15,
        defValue: 2,
        minWorldLevel: 3,
        chestChance: 15,
    },
    "Travelling Doctor's Handkerchief": {
        type: "Circlet",
        sellPrice: 6,
        attackPower: 0,
        critChance: 7,
        critValue: 0,
        maxHP: 0,
        defChance: 30,
        defValue: 1,
        minWorldLevel: 3,
        chestChance: 15,
    },
    "Berserker's Rose": {
        type: "Flower",
        sellPrice: 8,
        attackPower: 5,
        critChance: 10,
        critValue: 0,
        maxHP: -5,
        defChance: 0,
        defValue: 0,
        minWorldLevel: 4,
        chestChance: 15,
    },
    "Berserker's Indigo Feather": {
        type: "Plume",
        sellPrice: 8,
        attackPower: 5,
        critChance: 5,
        critValue: 0.5,
        maxHP: -20,
        defChance: 0,
        defValue: 0,
        minWorldLevel: 4,
        chestChance: 15,
    },
    "Berserker's Timepiece": {
        type: "Sands",
        sellPrice: 8,
        attackPower: 5,
        critChance: 10,
        critValue: 0.2,
        maxHP: -20,
        defChance: 0,
        defValue: 0,
        minWorldLevel: 4,
        chestChance: 15,
    },
    "Berserker's Bone Goblet": {
        type: "Goblet",
        sellPrice: 8,
        attackPower: 4,
        critChance: 10,
        critValue: 0.15,
        maxHP: -10,
        defChance: 0,
        defValue: -1,
        minWorldLevel: 4,
        chestChance: 15,
    },
    "Berserker's Battle Mask": {
        type: "Circlet",
        sellPrice: 8,
        attackPower: 4,
        critChance: 0,
        critValue: 0,
        maxHP: -5,
        defChance: 0,
        defValue: 0,
        minWorldLevel: 4,
        chestChance: 15,
    },
    "Exile's Flower": {
        type: "Flower",
        sellPrice: 10,
        attackPower: 0,
        critChance: 5,
        critValue: 0,
        maxHP: 15,
        defChance: 0,
        defValue: 0,
        minWorldLevel: 5,
        chestChance: 10,
    },
    "Exile's Feather": {
        type: "Plume",
        sellPrice: 10,
        attackPower: 6,
        critChance: 10,
        critValue: 1.25,
        maxHP: -10,
        defChance: 0,
        defValue: 0,
        minWorldLevel: 5,
        chestChance: 10,
    },
    "Exile's Pocket Watch": {
        type: "Sands",
        sellPrice: 10,
        attackPower: 4,
        critChance: 8,
        critValue: 0.5,
        maxHP: 5,
        defChance: 0,
        defValue: 0,
        minWorldLevel: 5,
        chestChance: 10,
    },
    "Exile's Goblet": {
        type: "Goblet",
        sellPrice: 10,
        attackPower: 3,
        critChance: 15,
        critValue: 0.75,
        maxHP: 0,
        defChance: -5,
        defValue: 0,
        minWorldLevel: 5,
        chestChance: 10,
    },
    "Exile's Circlet": {
        type: "Circlet",
        sellPrice: 10,
        attackPower: 2,
        critChance: 20,
        critValue: 0.25,
        maxHP: -10,
        defChance: 0,
        defValue: 0,
        minWorldLevel: 5,
        chestChance: 10,
    },

    "Guardian's Flower": {
        type: "Flower",
        sellPrice: 12,
        attackPower: -3,
        critChance: 0,
        critValue: 0,
        maxHP: 25,
        defChance: 10,
        defValue: 5,
        minWorldLevel: 6,
        chestChance: 8,
    },
    "Guardian's Sigil": {
        type: "Plume",
        sellPrice: 12,
        attackPower: 2,
        critChance: 0,
        critValue: 0,
        maxHP: 10,
        defChance: 20,
        defValue: 3,
        minWorldLevel: 6,
        chestChance: 8,
    },
    "Guardian's Clock": {
        type: "Sands",
        sellPrice: 12,
        attackPower: 1,
        critChance: 5,
        critValue: 0.5,
        maxHP: 20,
        defChance: 15,
        defValue: 6,
        minWorldLevel: 6,
        chestChance: 8,
    },
    "Guardian's Vessel": {
        type: "Goblet",
        sellPrice: 12,
        attackPower: 0,
        critChance: 0,
        critValue: 0,
        maxHP: 5,
        defChance: 25,
        defValue: 10,
        minWorldLevel: 6,
        chestChance: 8,
    },
    "Guardian's Band": {
        type: "Circlet",
        sellPrice: 12,
        attackPower: -5,
        critChance: 0,
        critValue: 0,
        maxHP: 15,
        defChance: 30,
        defValue: 5,
        minWorldLevel: 6,
        chestChance: 8,
    },
};

export type ArtifactName = keyof typeof artifacts;
export type ArtifactType = "Flower" | "Plume" | "Sands" | "Goblet" | "Circlet";

export function getArtifactType(artifact: ArtifactName): ArtifactType | null {
    if (!artifacts[artifact]) {
        return null;
    }
    return artifacts[artifact].type as ArtifactType;
}
