export const artifacts = {
    "Adventurer's Flower": {
        type: "Flower",
        sellPrice: 5,
        attackPower: 0,
        critChance: 0,
        critValue: 0,
        maxHP: 10,
        defChance: 0,
        defValue: 0,
    },
    "Adventurer's Tail Feather": {
        type: "Plume",
        sellPrice: 5,
        attackPower: 1.5,
        critChance: 0,
        critValue: 0,
        maxHP: 0,
        defChance: 0,
        defValue: 0,
    },
    "Adventurer's Pocket Watch": {
        type: "Sands",
        sellPrice: 5,
        attackPower: 1,
        critChance: 5,
        critValue: 0.25,
        maxHP: 5,
        defChance: 0,
        defValue: 0,
    },
    "Adventurer's Golden Goblet": {
        type: "Goblet",
        sellPrice: 5,
        attackPower: 0,
        critChance: 0,
        critValue: 0.5,
        maxHP: 0,
        defChance: 10,
        defValue: 1.5,
    },
    "Adventurer's Bandana": {
        type: "Circlet",
        sellPrice: 5,
        attackPower: 0,
        critChance: 15,
        critValue: 0,
        maxHP: 0,
        defChance: 0,
        defValue: 0,
    },
    "Travelling Doctor's Silver Lotus": {
        type: "Flower",
        sellPrice: 6,
        attackPower: -2,
        critChance: 0,
        critValue: 0,
        maxHP: 15,
        defChance: 5,
        defValue: 8,
    },
    "Travelling Doctor's Owl Feather": {
        type: "Plume",
        sellPrice: 6,
        attackPower: 2,
        critChance: 0,
        critValue: 0,
        maxHP: 0,
        defChance: 5,
        defValue: 4,
    },
    "Travelling Doctor's Pocket Watch": {
        type: "Sands",
        sellPrice: 6,
        attackPower: 2,
        critChance: 3,
        critValue: 0.3,
        maxHP: 10,
        defChance: 5,
        defValue: 3,
    },
    "Travelling Doctor's Medicine Pot": {
        type: "Goblet",
        sellPrice: 6,
        attackPower: 0,
        critChance: 0,
        critValue: 0.4,
        maxHP: 0,
        defChance: 15,
        defValue: 2,
    },
    "Travelling Doctor's Handkerchief": {
        type: "Circlet",
        sellPrice: 6,
        attackPower: 0,
        critChance: 10,
        critValue: 0,
        maxHP: 0,
        defChance: 30,
        defValue: 1,
    },
};

export type ArtifactName = keyof typeof artifacts;
export type ArtifactType = "Flower" | "Plume" | "Sands" | "Goblet" | "Circlet";

export function getArtifactType(artifact: ArtifactName): ArtifactType {
    return artifacts[artifact].type as ArtifactType;
}
