export const drops = {
    "Damaged Mask": {
        sellPrice: 5,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 1,
        chestChance: 25,
        rarity: 1,
    },
    "Stained Mask": {
        sellPrice: 10,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 2,
        chestChance: 15,
        rarity: 2,
    },
    "Ominous Mask": {
        sellPrice: 20,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 3,
        chestChance: 5,
        rarity: 3,
    },
    "Slime Condensate": {
        sellPrice: 3,
        minAmount: 1,
        maxAmount: 3,
        minWorldLevel: 1,
        chestChance: 25,
        rarity: 1,
    },
    "Slime Secretions": {
        sellPrice: 6,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 2,
        chestChance: 15,
        rarity: 2,
    },
    "Slime Concentrate": {
        sellPrice: 9,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 3,
        chestChance: 5,
        rarity: 3,
    },
    "Firm Arrowhead": {
        sellPrice: 5,
        minAmount: 1,
        maxAmount: 3,
        minWorldLevel: 1,
        chestChance: 25,
        rarity: 1,
    },
    "Sharp Arrowhead": {
        sellPrice: 10,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 2,
        chestChance: 15,
        rarity: 2,
    },
    "Weathered Arrowhead": {
        sellPrice: 15,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 2,
        chestChance: 15,
        rarity: 3,
    },
    "Divining Scroll": {
        sellPrice: 5,
        minAmount: 1,
        maxAmount: 3,
        minWorldLevel: 1,
        chestChance: 5,
        rarity: 1,
    },
    "Sealed Scroll": {
        sellPrice: 10,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 3,
        chestChance: 5,
        rarity: 2,
    },
    "Forbidden Curse Scroll": {
        sellPrice: 15,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 3,
        chestChance: 5,
        rarity: 3,
    },
    "Heavy Horn": {
        sellPrice: 5,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 6,
        chestChance: 5,
        rarity: 1,
    },
    "Black Bronze Horn": {
        sellPrice: 10,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 6,
        chestChance: 0,
        rarity: 2,
    },
    "Black Crystal Horn": {
        sellPrice: 15,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 6,
        chestChance: 0,
        rarity: 3,
    },
    "Treasure Hoarder Insignia": {
        sellPrice: 5,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 7,
        chestChance: 0,
        rarity: 1,
    },
    "Silver Raven Insignia": {
        sellPrice: 10,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 7,
        chestChance: 0,
        rarity: 2,
    },
    "Golden Raven Insignia": {
        sellPrice: 15,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 7,
        chestChance: 0,
        rarity: 3,
    },
    "Dead Ley Line Branch": {
        sellPrice: 5,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 7,
        chestChance: 0,
        rarity: 1,
    },
    "Dead Ley Line Leaves": {
        sellPrice: 10,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 7,
        chestChance: 0,
        rarity: 2,
    },
    "Ley Line Sprout": {
        sellPrice: 15,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 7,
        chestChance: 0,
        rarity: 3,
    },
    "Recruit's Insignia": {
        sellPrice: 20,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 5,
        rarity: 1,
    },
    "Sergeant's Insignia": {
        sellPrice: 25,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 2,
    },
    "Lieutenant's Insignia": {
        sellPrice: 30,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 3,
    },
    "Dismal Prism": {
        sellPrice: 20,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 1,
    },
    "Crystal Prism": {
        sellPrice: 25,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 2,
    },
    "Polarizing Prism": {
        sellPrice: 30,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 3,
    },
    "Mist Grass Pollen": {
        sellPrice: 20,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 5,
        rarity: 1,
    },
    "Mist Grass": {
        sellPrice: 25,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 2,
    },
    "Mist Grass Wick": {
        sellPrice: 30,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 3,
    },
    "Hunter's Sacrificial Knife": {
        sellPrice: 20,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 5,
        rarity: 1,
    },
    "Agent's Sacrificial Knife": {
        sellPrice: 25,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 2,
    },
    "Inspector's Sacrificial Knife": {
        sellPrice: 25,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 3,
    },
    "A Flower Yet to Bloom": {
        sellPrice: 15,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 1,
    },
    "Treasured Flower": {
        sellPrice: 20,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 2,
    },
    "Wanderer's Blooming Flower": {
        sellPrice: 25,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 3,
    },
    "Faded Red Satin": {
        sellPrice: 5,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 13,
        chestChance: 0,
        rarity: 1,
    },
    "Trimmed Red Silk": {
        sellPrice: 10,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 13,
        chestChance: 0,
        rarity: 2,
    },
    "Rich Red Brocade": {
        sellPrice: 15,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 13,
        chestChance: 0,
        rarity: 3,
    },
    "Chaos Device": {
        sellPrice: 5,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 1,
    },
    "Chaos Circuit": {
        sellPrice: 5,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 2,
    },
    "Chaos Core": {
        sellPrice: 5,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 11,
        chestChance: 0,
        rarity: 3,
    },
    "Chaos Gear": {
        sellPrice: 25,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 1,
        chestChance: 0,
        rarity: 1,
    },
    "Chaos Axis": {
        sellPrice: 30,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 1,
        chestChance: 0,
        rarity: 2,
    },
    "Chaos Oculus": {
        sellPrice: 35,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 1,
        chestChance: 0,
        rarity: 3,
    },
    "Old Handguard": {
        sellPrice: 25,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 20,
        chestChance: 0,
        rarity: 1,
    },
    "Kageuchi Handguard": {
        sellPrice: 30,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 20,
        chestChance: 0,
        rarity: 2,
    },
    "Famed Handguard": {
        sellPrice: 35,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 20,
        chestChance: 0,
        rarity: 3,
    },
    "Old Operative's Pocket Watch": {
        sellPrice: 25,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 20,
        chestChance: 2,
        rarity: 1,
    },
    "Operative's Standard Pocket Watch": {
        sellPrice: 30,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 20,
        chestChance: 2,
        rarity: 2,
    },
    "Operative's Constancy": {
        sellPrice: 40,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 20,
        chestChance: 2,
        rarity: 3,
    },
    "Concealed Claw": {
        sellPrice: 30,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 30,
        chestChance: 1,
        rarity: 1,
    },
    "Concealed Unguis": {
        sellPrice: 40,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 30,
        chestChance: 1,
        rarity: 2,
    },
    "Life Essence": {
        sellPrice: 1,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 1,
        chestChance: 0,
        rarity: 3,
    },
    Geode: {
        sellPrice: 125,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 10,
        chestChance: 0,
        rarity: 3,
    },
};

export type DropName = keyof typeof drops;
