export const drops = {
    "Damaged Mask": {
        sellPrice: 5,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 1,
        chestChance: 25,
    },
    "Stained Mask": {
        sellPrice: 10,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 2,
        chestChance: 15,
    },
    "Ominous Mask": {
        sellPrice: 20,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 3,
        chestChance: 5,
    },
    "Slime Condensate": {
        sellPrice: 3,
        minAmount: 1,
        maxAmount: 3,
        minWorldLevel: 1,
        chestChance: 25,
    },
    "Slime Secretions": {
        sellPrice: 6,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 2,
        chestChance: 15,
    },
    "Slime Concentrate": {
        sellPrice: 9,
        minAmount: 1,
        maxAmount: 1,
        minWorldLevel: 3,
        chestChance: 5,
    },
    "Firm Arrowhead": {
        sellPrice: 5,
        minAmount: 1,
        maxAmount: 3,
        minWorldLevel: 1,
        chestChance: 25,
    },
    "Sharp Arrowhead": {
        sellPrice: 10,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 2,
        chestChance: 15,
    },
    "Weathered Arrowhead": {
        sellPrice: 15,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 2,
        chestChance: 15,
    },
    "Divining Scroll": {
        sellPrice: 5,
        minAmount: 1,
        maxAmount: 3,
        minWorldLevel: 1,
        chestChance: 5,
    },
    "Sealed Scroll": {
        sellPrice: 10,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 3,
        chestChance: 5,
    },
    "Forbidden Curse Scroll": {
        sellPrice: 15,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 3,
        chestChance: 5,
    },
    "Heavy Horn": {
        sellPrice: 5,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 6,
        chestChance: 5,
    },
    "Black Bronze Horn": {
        sellPrice: 10,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 6,
        chestChance: 0,
    },
    "Black Crystal Horn": {
        sellPrice: 15,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 6,
        chestChance: 0,
    },
    "Treasure Hoarder Insignia": {
        sellPrice: 5,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 7,
        chestChance: 5,
    },
    "Silver Raven Insignia": {
        sellPrice: 10,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 7,
        chestChance: 0,
    },
    "Golden Raven Insignia": {
        sellPrice: 15,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 7,
        chestChance: 0,
    },
    "Dead Ley Line Branch": {
        sellPrice: 5,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 7,
        chestChance: 5,
    },
    "Dead Ley Line Leaves": {
        sellPrice: 10,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 7,
        chestChance: 2,
    },
    "Ley Line Sprout": {
        sellPrice: 15,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 7,
        chestChance: 0,
    },
    "Recruit's Insignia": {
        sellPrice: 20,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 5,
    },
    "Sergeant's Insignia": {
        sellPrice: 25,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
    },
    "Dismal Prism": {
        sellPrice: 20,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 5,
    },
    "Crystal Prism": {
        sellPrice: 25,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
    },
    "Mist Grass Pollen": {
        sellPrice: 20,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 5,
    },
    "Mist Grass": {
        sellPrice: 25,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
    },
    "Hunter's Sacrificial Knife": {
        sellPrice: 20,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 5,
    },
    "Agent's Sacrificial Knife": {
        sellPrice: 25,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
    },
    "A Flower Yet to Bloom": {
        sellPrice: 20,
        minAmount: 1,
        maxAmount: 2,
        minWorldLevel: 11,
        chestChance: 0,
    },
    "Metal Scrap": {
        sellPrice: 5,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 1,
        chestChance: 0,
    },
    "Chaos Gear": {
        sellPrice: 25,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 1,
        chestChance: 0,
    },
    "Chaos Axis": {
        sellPrice: 30,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 1,
        chestChance: 0,
    },
    "Chaos Device": {
        sellPrice: 25,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 1,
        chestChance: 0,
    },
    "Chaos Circuit": {
        sellPrice: 30,
        minAmount: 0,
        maxAmount: 0,
        minWorldLevel: 1,
        chestChance: 0,
    },
};

export type DropName = keyof typeof drops;
