export type FishRarity = "Common" | "Rare" | "Epic" | "Legendary";

export interface FishData {
    rarity: FishRarity;
    fishingLevel: number;
    weight: number;
    sellPrice: number;
    rods: string[];
    minReels: number;
    maxReels: number;
    minExp: number;
    maxExp: number;
}

export const fish: { [key: string]: FishData } = {
    Betta: {
        rarity: "Common",
        fishingLevel: 1,
        weight: 50,
        sellPrice: 15,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 1,
        maxReels: 2,
        minExp: 10,
        maxExp: 20,
    },
    "Lunged Stickleback": {
        rarity: "Common",
        fishingLevel: 1,
        weight: 50,
        sellPrice: 20,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 1,
        maxReels: 2,
        minExp: 10,
        maxExp: 20,
    },
    Medaka: {
        rarity: "Common",
        fishingLevel: 1,
        weight: 50,
        sellPrice: 25,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 1,
        maxReels: 3,
        minExp: 15,
        maxExp: 25,
    },
    "Aizen Medaka": {
        rarity: "Common",
        fishingLevel: 1,
        weight: 50,
        sellPrice: 20,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 1,
        maxReels: 3,
        minExp: 15,
        maxExp: 25,
    },
    "Venomspine Fish": {
        rarity: "Common",
        fishingLevel: 2,
        weight: 50,
        sellPrice: 30,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 2,
        maxReels: 4,
        minExp: 20,
        maxExp: 35,
    },
    "Golden Koi": {
        rarity: "Rare",
        fishingLevel: 2,
        weight: 30,
        sellPrice: 75,
        rods: ["Wavepiercer", "Moonstringer", "Windtangler", "Serendipity"],
        minReels: 3,
        maxReels: 5,
        minExp: 40,
        maxExp: 60,
    },
    "Purple Shirakodai": {
        rarity: "Common",
        fishingLevel: 3,
        weight: 50,
        sellPrice: 35,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 2,
        maxReels: 4,
        minExp: 25,
        maxExp: 40,
    },
    "Glaze Medaka": {
        rarity: "Common",
        fishingLevel: 3,
        weight: 50,
        sellPrice: 30,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 1,
        maxReels: 3,
        minExp: 25,
        maxExp: 40,
    },
    "Abiding Angelfish": {
        rarity: "Epic",
        fishingLevel: 3,
        weight: 15,
        sellPrice: 125,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 4,
        maxReels: 6,
        minExp: 80,
        maxExp: 120,
    },
    "Rusty Koi": {
        rarity: "Rare",
        fishingLevel: 4,
        weight: 30,
        sellPrice: 100,
        rods: ["Moonstringer", "Windtangler", "Serendipity"],
        minReels: 3,
        maxReels: 5,
        minExp: 50,
        maxExp: 75,
    },
    Snowstrider: {
        rarity: "Legendary",
        fishingLevel: 5,
        weight: 1,
        sellPrice: 500,
        rods: ["Windtangler", "Serendipity"],
        minReels: 5,
        maxReels: 7,
        minExp: 150,
        maxExp: 200,
    },
    Crystalfish: {
        rarity: "Legendary",
        fishingLevel: 6,
        weight: 1,
        sellPrice: 500,
        rods: ["Serendipity"],
        minReels: 7,
        maxReels: 9,
        minExp: 200,
        maxExp: 250,
    },
    "Akai Maou": {
        rarity: "Common",
        fishingLevel: 6,
        weight: 50,
        sellPrice: 30,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 1,
        maxReels: 3,
        minExp: 35,
        maxExp: 50,
    },
    // Non Genshin
    Anchovy: {
        rarity: "Common",
        fishingLevel: 2,
        weight: 50,
        sellPrice: 10,
        rods: ["Wilderness Rod", "Wishmaker", "Narukawa Ukai", "Wavepiercer"],
        minReels: 1,
        maxReels: 2,
        minExp: 15,
        maxExp: 25,
    },
    Sardine: {
        rarity: "Common",
        fishingLevel: 2,
        weight: 50,
        sellPrice: 15,
        rods: ["Wilderness Rod", "Wishmaker", "Narukawa Ukai", "Wavepiercer"],
        minReels: 1,
        maxReels: 2,
        minExp: 15,
        maxExp: 25,
    },
    Bream: {
        rarity: "Rare",
        fishingLevel: 3,
        weight: 30,
        sellPrice: 50,
        rods: ["Wavepiercer", "Moonstringer", "Windtangler"],
        minReels: 3,
        maxReels: 5,
        minExp: 45,
        maxExp: 65,
    },
    Perch: {
        rarity: "Rare",
        fishingLevel: 4,
        weight: 30,
        sellPrice: 60,
        rods: ["Moonstringer", "Windtangler", "Serendipity"],
        minReels: 3,
        maxReels: 5,
        minExp: 50,
        maxExp: 75,
    },
    "Duskhaven Snapper": {
        rarity: "Rare",
        fishingLevel: 4,
        weight: 25,
        sellPrice: 70,
        rods: ["Moonstringer", "Windtangler", "Serendipity"],
        minReels: 3,
        maxReels: 5,
        minExp: 55,
        maxExp: 80,
    },
    "Marsh Perch": {
        rarity: "Rare",
        fishingLevel: 4,
        weight: 12,
        sellPrice: 80,
        rods: ["Moonstringer", "Windtangler"],
        minReels: 3,
        maxReels: 5,
        minExp: 60,
        maxExp: 85,
    },
    "Amberfin Catfish": {
        rarity: "Epic",
        fishingLevel: 5,
        weight: 6,
        sellPrice: 150,
        rods: ["Windtangler", "Wilderness Rod"],
        minReels: 4,
        maxReels: 6,
        minExp: 100,
        maxExp: 140,
    },
    "Silverfin Trout": {
        rarity: "Epic",
        fishingLevel: 5,
        weight: 5,
        sellPrice: 180,
        rods: ["Windtangler", "Narukawa Ukai"],
        minReels: 4,
        maxReels: 6,
        minExp: 110,
        maxExp: 150,
    },
    Carp: {
        rarity: "Epic",
        fishingLevel: 5,
        weight: 15,
        sellPrice: 75,
        rods: ["Windtangler", "Serendipity"],
        minReels: 4,
        maxReels: 6,
        minExp: 90,
        maxExp: 130,
    },
    "Twilight Gourami": {
        rarity: "Epic",
        fishingLevel: 6,
        weight: 14,
        sellPrice: 200,
        rods: ["Wavepiercer", "Wilderness Rod"],
        minReels: 5,
        maxReels: 7,
        minExp: 120,
        maxExp: 160,
    },
    Salmon: {
        rarity: "Epic",
        fishingLevel: 6,
        weight: 15,
        sellPrice: 100,
        rods: ["Windtangler", "Serendipity"],
        minReels: 5,
        maxReels: 7,
        minExp: 100,
        maxExp: 140,
    },
};

export type FishName = keyof typeof fish;

export const fishList: (FishData & { name: string })[] = Object.entries(
    fish,
).map(([name, data]) => ({ name, ...data }));
