export type FishRarity = "Common" | "Rare" | "Epic" | "Legendary";

export interface FishData {
    rarity: FishRarity;
    fishingLevel: number;
    weight: number;
    sellPrice: number;
    rods: string[];
    minReels: number;
    maxReels: number;
}

export const fish: { [key: string]: FishData } = {
    Betta: {
        rarity: "Common",
        fishingLevel: 1,
        weight: 50,
        sellPrice: 15,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 1,
        maxReels: 2,
    },
    "Lunged Stickleback": {
        rarity: "Common",
        fishingLevel: 1,
        weight: 50,
        sellPrice: 20,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 1,
        maxReels: 2,
    },
    Medaka: {
        rarity: "Common",
        fishingLevel: 1,
        weight: 50,
        sellPrice: 25,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 1,
        maxReels: 3,
    },
    "Aizen Medaka": {
        rarity: "Common",
        fishingLevel: 1,
        weight: 50,
        sellPrice: 20,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 1,
        maxReels: 3,
    },
    "Venomspine Fish": {
        rarity: "Common",
        fishingLevel: 2,
        weight: 50,
        sellPrice: 30,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 2,
        maxReels: 4,
    },
    "Golden Koi": {
        rarity: "Rare",
        fishingLevel: 2,
        weight: 30,
        sellPrice: 75,
        rods: ["Wavepiercer", "Moonstringer", "Windtangler", "Serendipity"],
        minReels: 3,
        maxReels: 5,
    },
    "Purple Shirakodai": {
        rarity: "Common",
        fishingLevel: 3,
        weight: 50,
        sellPrice: 35,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 2,
        maxReels: 4,
    },
    "Glaze Medaka": {
        rarity: "Common",
        fishingLevel: 3,
        weight: 50,
        sellPrice: 30,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 1,
        maxReels: 3,
    },
    "Abiding Angelfish": {
        rarity: "Epic",
        fishingLevel: 3,
        weight: 15,
        sellPrice: 125,
        rods: [
            "Wilderness Rod",
            "Wishmaker",
            "Narukawa Ukai",
            "Wavepiercer",
            "Moonstringer",
            "Windtangler",
            "Serendipity",
        ],
        minReels: 4,
        maxReels: 6,
    },
    "Rusty Koi": {
        rarity: "Rare",
        fishingLevel: 4,
        weight: 30,
        sellPrice: 100,
        rods: ["Moonstringer", "Windtangler", "Serendipity"],
        minReels: 3,
        maxReels: 5,
    },
    Snowstrider: {
        rarity: "Legendary",
        fishingLevel: 5,
        weight: 1,
        sellPrice: 500,
        rods: ["Windtangler", "Serendipity"],
        minReels: 5,
        maxReels: 7,
    },
    Crystalfish: {
        rarity: "Legendary",
        fishingLevel: 6,
        weight: 1,
        sellPrice: 500,
        rods: ["Serendipity"],
        minReels: 7,
        maxReels: 9,
    },
    // Non Genshin
    Anchovy: {
        rarity: "Common",
        fishingLevel: 2,
        weight: 50,
        sellPrice: 10,
        rods: ["Wilderness Rod", "Wishmaker", "Narukawa Ukai", "Wavepiercer"],
        minReels: 1,
        maxReels: 2,
    },
    Sardine: {
        rarity: "Common",
        fishingLevel: 2,
        weight: 50,
        sellPrice: 15,
        rods: ["Wilderness Rod", "Wishmaker", "Narukawa Ukai", "Wavepiercer"],
        minReels: 1,
        maxReels: 2,
    },
    Bream: {
        rarity: "Rare",
        fishingLevel: 3,
        weight: 30,
        sellPrice: 50,
        rods: ["Wavepiercer", "Moonstringer", "Windtangler"],
        minReels: 3,
        maxReels: 5,
    },
    Perch: {
        rarity: "Rare",
        fishingLevel: 4,
        weight: 30,
        sellPrice: 60,
        rods: ["Moonstringer", "Windtangler", "Serendipity"],
        minReels: 3,
        maxReels: 5,
    },
    Carp: {
        rarity: "Epic",
        fishingLevel: 5,
        weight: 15,
        sellPrice: 200,
        rods: ["Windtangler", "Serendipity"],
        minReels: 4,
        maxReels: 6,
    },
    Salmon: {
        rarity: "Epic",
        fishingLevel: 6,
        weight: 15,
        sellPrice: 300,
        rods: ["Windtangler", "Serendipity"],
        minReels: 5,
        maxReels: 7,
    },
};

export type FishName = keyof typeof fish;

export const fishList: (FishData & { name: string })[] = Object.entries(
    fish,
).map(([name, data]) => ({ name, ...data }));
