export const misc = {
    "Bird Egg": {
        sellPrice: 1,
        minAmount: 1,
        maxAmount: 2,
        dropChance: 10,
    },
    Potato: {
        sellPrice: 1,
        minAmount: 1,
        maxAmount: 3,
        dropChance: 15,
    },
    Carrot: {
        sellPrice: 1,
        minAmount: 1,
        maxAmount: 4,
        dropChance: 12,
    },
    Apple: {
        sellPrice: 2,
        minAmount: 1,
        maxAmount: 3,
        dropChance: 8,
    },
    Sunsetta: {
        sellPrice: 2,
        minAmount: 2,
        maxAmount: 5,
        dropChance: 7,
    },
    Wheat: {
        sellPrice: 1,
        minAmount: 1,
        maxAmount: 6,
        dropChance: 18,
    },
    Mushroom: {
        sellPrice: 1,
        minAmount: 1,
        maxAmount: 6,
        dropChance: 18,
    },
    Raddish: {
        sellPrice: 1,
        minAmount: 1,
        maxAmount: 3,
        dropChance: 10,
    },
    Mint: {
        sellPrice: 1,
        minAmount: 1,
        maxAmount: 3,
        dropChance: 10,
    },
    Snapdragon: {
        sellPrice: 3,
        minAmount: 1,
        maxAmount: 2,
        dropChance: 9,
    },
    Cabbage: {
        sellPrice: 1,
        minAmount: 1,
        maxAmount: 2,
        dropChance: 11,
    },
    Pinecone: {
        sellPrice: 1,
        minAmount: 1,
        maxAmount: 3,
        dropChance: 16,
    },
    "Lotus Head": {
        sellPrice: 2,
        minAmount: 1,
        maxAmount: 2,
        dropChance: 7,
    },
    Berry: {
        sellPrice: 1,
        minAmount: 2,
        maxAmount: 2,
        dropChance: 17,
    },
    Violetgras: {
        sellPrice: 3,
        minAmount: 1,
        maxAmount: 2,
        dropChance: 6,
    },
    Crab: {
        sellPrice: 4,
        minAmount: 1,
        maxAmount: 2,
        dropChance: 5,
    },
    Matsutake: {
        sellPrice: 2,
        minAmount: 1,
        maxAmount: 3,
        dropChance: 8,
    },
    Fowl: {
        sellPrice: 3,
        minAmount: 1,
        maxAmount: 2,
        dropChance: 10,
    },
    Onion: {
        sellPrice: 1,
        minAmount: 1,
        maxAmount: 3,
        dropChance: 14,
    },
    Fish: {
        sellPrice: 4,
        minAmount: 1,
        maxAmount: 2,
        dropChance: 9,
    },
    Almond: {
        sellPrice: 3,
        minAmount: 1,
        maxAmount: 2,
        dropChance: 7,
    },
};

export type MiscName = keyof typeof misc;
