export const weapons = {
    "Dull Blade": {
        sellPrice: 5,
        attackPower: 2,
        critChance: 0,
        critValue: 0,
        minWorldLevel: 1,
        chestChance: 30,
    },
    "Waster Greatsword": {
        sellPrice: 5,
        attackPower: 3.5,
        critChance: 10,
        critValue: 1.5,
        minWorldLevel: 2,
        chestChance: 20,
    },
    "Iron Point": {
        sellPrice: 8,
        attackPower: 4,
        critChance: 15,
        critValue: 1.75,
        minWorldLevel: 3,
        chestChance: 10,
    },
    "Silver Sword": {
        sellPrice: 8,
        attackPower: 4.5,
        critChance: 15,
        critValue: 2,
        minWorldLevel: 3,
        chestChance: 5,
    },
    "Cool Steel": {
        sellPrice: 10,
        attackPower: 5,
        critChance: 15,
        critValue: 2.5,
        minWorldLevel: 4,
        chestChance: 5,
    },
    "White Tassel": {
        sellPrice: 10,
        attackPower: 0,
        critChance: 50,
        critValue: 1.5,
        minWorldLevel: 4,
        chestChance: 5,
    },
    "Skyrider Sword": {
        sellPrice: 15,
        attackPower: 6,
        critChance: 20,
        critValue: 1.5,
        minWorldLevel: 5,
        chestChance: 5,
    },
    "Twin Nephrite": {
        sellPrice: 15,
        attackPower: 2,
        critChance: 5,
        critValue: 5,
        minWorldLevel: 5,
        chestChance: 5,
    },
};

export type WeaponName = keyof typeof weapons;
