import { make } from "@elara-services/utils";

export type WeaponType =
    | "Claymore"
    | "Bow"
    | "Sword"
    | "Catalyst"
    | "Polearm"
    | "Rod";

interface WeaponData {
    name: string;
    type: WeaponType;
    sellPrice: number;
    attackPower: number;
    critChance: number;
    critValue: number;
    defValue: number;
    defChance: number;
    additionalHP: number;
    minadventurerank: number;
    chestChance: number;
    emoji: string;
    imageURL: string;
    additionalMana: number;
}

const baseWeapons: { [key: string]: WeaponData } = {
    "Dull Blade": {
        name: "Dull Blade",
        type: "Sword",
        sellPrice: 5,
        attackPower: 2,
        critChance: 0,
        critValue: 0,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 1,
        chestChance: 30,
        emoji: "<:Weapon_Dull_Blade:1282455010222800968>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/dull_blade.png",
    },
    "Waster Greatsword": {
        name: "Waster Greatsword",
        type: "Claymore",
        sellPrice: 5,
        attackPower: 3.5,
        critChance: 10,
        critValue: 0.25,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 2,
        chestChance: 20,
        emoji: "<:Weapon_Waster_Greatsword:1282455085741510857>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/waster_greatsword.png",
    },
    "Iron Point": {
        name: "Iron Point",
        type: "Polearm",
        sellPrice: 5,
        attackPower: 4,
        critChance: 15,
        critValue: 0.5,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 3,
        chestChance: 10,
        emoji: "<:Weapon_Iron_Point:1282455154427170987>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/iron_point.png",
    },
    "Silver Sword": {
        name: "Silver Sword",
        type: "Sword",
        sellPrice: 5,
        attackPower: 4.5,
        critChance: 15,
        critValue: 0.5,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 3,
        chestChance: 5,
        emoji: "<:Weapon_Silver_Sword:1282455291153223774>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/silver_sword.png",
    },
    "Cool Steel": {
        name: "Cool Steel",
        type: "Sword",
        sellPrice: 5,
        attackPower: 5,
        critChance: 15,
        critValue: 0.75,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 4,
        chestChance: 5,
        emoji: "<:Weapon_Cool_Steel:1282455365161582643>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/cool_steel.png",
    },
    "White Tassel": {
        name: "White Tassel",
        type: "Polearm",
        sellPrice: 5,
        attackPower: 0,
        critChance: 50,
        critValue: 0.5,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 4,
        chestChance: 5,
        emoji: "<:Weapon_White_Tassel:1282455432715047003>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/white_tassel.png",
    },
    "Wilderness Rod": {
        name: "Wilderness Rod",
        type: "Rod",
        sellPrice: 0,
        attackPower: 1,
        critChance: 0,
        critValue: 0,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 5,
        chestChance: 10,
        emoji: "<:Item_Wilderness_Rod1:1309627118803750932>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/wilderness_rod.png",
    },
    "Skyrider Sword": {
        name: "Skyrider Sword",
        type: "Sword",
        sellPrice: 10,
        attackPower: 6,
        critChance: 20,
        critValue: 0.75,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 5,
        chestChance: 5,
        emoji: "<:Weapon_Skyrider_Sword:1282455504269869109>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/skyrider_sword.png",
    },
    "Twin Nephrite": {
        name: "Twin Nephrite",
        type: "Catalyst",
        sellPrice: 10,
        attackPower: 0,
        critChance: 5,
        critValue: 3,
        defValue: 0,
        defChance: 0,
        additionalHP: -10,
        additionalMana: 5,
        minadventurerank: 5,
        chestChance: 5,
        emoji: "<:Weapon_Twin_Nephrite:1282455571370606653>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/twin_nephrite.png",
    },
    "Harbinger of Dawn": {
        name: "Harbinger of Dawn",
        type: "Sword",
        sellPrice: 15,
        attackPower: 8,
        critChance: 25,
        critValue: 1.5,
        defValue: 0,
        defChance: 0,
        additionalHP: 20,
        additionalMana: 0,
        minadventurerank: 6,
        chestChance: 5,
        emoji: "<:Weapon_Harbinger_of_Dawn:1282455645273981039>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/harbinger_of_dawn.png",
    },
    "Magic Guide": {
        name: "Magic Guide",
        type: "Catalyst",
        sellPrice: 15,
        attackPower: 8,
        critChance: 10,
        critValue: 0.5,
        defValue: 0,
        defChance: 0,
        additionalHP: -25,
        additionalMana: 3,
        minadventurerank: 6,
        chestChance: 10,
        emoji: "<:Weapon_Magic_Guide:1282455719580270624>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/magic_guide.png",
    },
    Messenger: {
        name: "Messenger",
        type: "Bow",
        sellPrice: 15,
        attackPower: 12,
        critChance: 5,
        critValue: 1,
        defValue: 0,
        defChance: 0,
        additionalHP: 30,
        additionalMana: 0,
        minadventurerank: 6,
        chestChance: 5,
        emoji: "<:Weapon_Messenger:1282455784940245032>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/messenger.png",
    },
    Wishmaker: {
        name: "Wishmaker",
        type: "Rod",
        sellPrice: 0,
        attackPower: 3,
        critChance: 10,
        critValue: 0,
        defValue: 0,
        defChance: 0,
        additionalHP: 50,
        additionalMana: 0,
        minadventurerank: 5,
        chestChance: 10,
        emoji: "<:Item_Wishmaker:1309629861081387080>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/wishmaker.png",
    },
    "Raven Bow": {
        name: "Raven Bow",
        type: "Bow",
        sellPrice: 15,
        attackPower: 15,
        critChance: 15,
        critValue: 0.75,
        defValue: 0,
        defChance: 0,
        additionalHP: -15,
        additionalMana: 0,
        minadventurerank: 7,
        chestChance: 5,
        emoji: "<:Weapon_Raven_Bow:1282455848810971136>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/raven_bow.png",
    },
    "Recurve Bow": {
        name: "Recurve Bow",
        type: "Bow",
        sellPrice: 15,
        attackPower: 13,
        critChance: 10,
        critValue: 0.5,
        defValue: 0,
        defChance: 0,
        additionalHP: 40,
        additionalMana: 0,
        minadventurerank: 7,
        chestChance: 5,
        emoji: "<:Weapon_Recurve_Bow:1282455914556952576>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/recurve_bow.png",
    },
    "Otherworldly Story": {
        name: "Otherworldly Story",
        type: "Catalyst",
        sellPrice: 15,
        attackPower: 15,
        critChance: 25,
        critValue: 1,
        defValue: 0,
        defChance: 0,
        additionalHP: -50,
        additionalMana: 10,
        minadventurerank: 7,
        chestChance: 5,
        emoji: "<:Weapon_Otherworldly_Story:1282455997994238033>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/otherworldly_story.png",
    },
    "The Black Sword": {
        name: "The Black Sword",
        type: "Sword",
        sellPrice: 15,
        attackPower: 2,
        critChance: -40,
        critValue: 4,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 7,
        chestChance: 5,
        emoji: "<:Weapon_The_Black_Sword:1282998131432230933>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/the_black-sword.png",
    },
    "The Bell": {
        name: "The Bell",
        type: "Claymore",
        sellPrice: 15,
        attackPower: 0,
        critChance: -20,
        critValue: -1,
        defValue: 0,
        defChance: 0,
        additionalHP: 125,
        additionalMana: 0,
        minadventurerank: 7,
        chestChance: 5,
        emoji: "<:Weapon_The_Bell:1282998169830952960>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/the_bell.png",
    },
    "Emerald Orb": {
        name: "Emerald orb",
        type: "Catalyst",
        sellPrice: 15,
        attackPower: 12,
        critChance: 20,
        critValue: 0.75,
        defValue: 0,
        defChance: 0,
        additionalHP: -100,
        additionalMana: 6,
        minadventurerank: 8,
        chestChance: 5,
        emoji: "<:Weapon_Emerald_Orb:1282456084505952286>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/emerald_orb.png",
    },
    "The Halberd": {
        name: "The Halberd",
        type: "Polearm",
        sellPrice: 15,
        attackPower: 15,
        critChance: 0,
        critValue: 0.1,
        defValue: 0,
        defChance: 0,
        additionalHP: 5,
        additionalMana: 0,
        minadventurerank: 8,
        chestChance: 5,
        emoji: "<:Weapon_Halberd:1291432656986312766>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/the_halberd.png",
    },
    "Ferrous Shadow": {
        name: "Ferrous Shadow",
        type: "Sword",
        sellPrice: 30,
        attackPower: 15,
        critChance: 5,
        critValue: 0.5,
        defValue: 0,
        defChance: 0,
        additionalHP: 50,
        additionalMana: 0,
        minadventurerank: 8,
        chestChance: 5,
        emoji: "<:Weapon_Ferrous_Shadow:1282456147210535013>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/ferrous_shadow.png",
    },
    "Fillet Blade": {
        name: "Fillet Blade",
        type: "Sword",
        sellPrice: 30,
        attackPower: 17,
        critChance: 5,
        critValue: 0.8,
        defValue: 0,
        defChance: 25,
        additionalHP: -25,
        additionalMana: 0,
        minadventurerank: 8,
        chestChance: 5,
        emoji: "<:Weapon_Fillet_Blade:1282456217150558258>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/fillet_blade.png",
    },
    "Sacrificial Sword": {
        name: "Sacrificial Sword",
        type: "Sword",
        sellPrice: 30,
        attackPower: 10,
        critChance: 0,
        critValue: 0.5,
        defValue: 0,
        defChance: 0,
        additionalHP: 50,
        additionalMana: 0,
        minadventurerank: 8,
        chestChance: 5,
        emoji: "<:Weapon_Sacrificial_Sword:1282504118518284338>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/sacrificial_sword.png",
    },
    "The Widsith": {
        name: "The Widsith",
        type: "Catalyst",
        sellPrice: 30,
        attackPower: 0,
        critChance: 90,
        critValue: 0,
        defValue: -25,
        defChance: 0,
        additionalHP: -100,
        additionalMana: 10,
        minadventurerank: 8,
        chestChance: 5,
        emoji: "<:Weapon_The_Widsith:1291432715622547478>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/the_widsith.png",
    },
    "The Flute": {
        name: "The Flute",
        type: "Sword",
        sellPrice: 30,
        attackPower: 15,
        critChance: 40,
        critValue: 0.5,
        defValue: 0,
        defChance: 0,
        additionalHP: -50,
        additionalMana: 0,
        minadventurerank: 8,
        chestChance: 5,
        emoji: "<:Weapon_The_Flute:1282504448538837013>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/the_flute.png",
    },
    "Narukawa Ukai": {
        name: "Narukawa Ukai",
        type: "Rod",
        sellPrice: 0,
        attackPower: 7,
        critChance: 10,
        critValue: 0,
        defValue: 0,
        defChance: 0,
        additionalHP: 50,
        additionalMana: 0,
        minadventurerank: 10,
        chestChance: 10,
        emoji: "<:Item_Narukawa_Ukai:1309632037803528242>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/narukawa_ukai.png",
    },
    "Blackcliff Agate": {
        name: "Blackcliff Agate",
        type: "Catalyst",
        sellPrice: 30,
        attackPower: 17,
        critChance: 20,
        critValue: 1,
        defValue: 10,
        defChance: -10,
        additionalHP: 75,
        additionalMana: 5,
        minadventurerank: 10,
        chestChance: 5,
        emoji: "<:Weapon_Blackcliff_Agate:1284390885836066847>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/blackcliff_agate.png",
    },
    "Chain Breaker": {
        name: "Chain Breaker",
        type: "Bow",
        sellPrice: 30,
        attackPower: 20,
        critChance: 20,
        critValue: 1,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 10,
        chestChance: 5,
        emoji: "<:Weapon_Chain_Breaker:1284617740899844176>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/chain_breaker.png",
    },
    "Cinnabar Spindle": {
        name: "Cinnabar Spindle",
        type: "Sword",
        sellPrice: 30,
        attackPower: 20,
        critChance: 0,
        critValue: 2,
        defValue: 100,
        defChance: 10,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 10,
        chestChance: 5,
        emoji: "<:Weapon_Cinnabar_Spindle:1292283663329005621>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/cinnabar_spindle.png",
    },
    Deathmatch: {
        name: "Deathmatch",
        type: "Polearm",
        sellPrice: 30,
        attackPower: 15,
        critChance: -80,
        critValue: 10,
        defValue: 20,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 10,
        chestChance: 5,
        emoji: "<:Weapon_Deathmatch:1284617953509245082>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/deathmatch.png",
    },
    "The Stringless": {
        name: "The Stringless",
        type: "Bow",
        sellPrice: 30,
        attackPower: 20,
        critChance: 5,
        critValue: 0.25,
        defValue: 20,
        defChance: 0,
        additionalHP: 10,
        additionalMana: 0,
        minadventurerank: 10,
        chestChance: 5,
        emoji: "<:Weapon_The_Stringless:1291432822808117338>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/the_stringless.png",
    },
    Wavepiercer: {
        name: "Wavepiercer",
        type: "Rod",
        sellPrice: 0,
        attackPower: 14,
        critChance: 10,
        critValue: 1.5,
        defValue: 50,
        defChance: 0,
        additionalHP: 75,
        additionalMana: 0,
        minadventurerank: 12,
        chestChance: 10,
        emoji: "<:Item_Wavepiercer:1309632428935090176>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/wavepiercer.png",
    },
    "Vortex Vanquisher": {
        name: "Vortex Vanquisher",
        type: "Polearm",
        sellPrice: 50,
        attackPower: -75,
        critChance: 5,
        critValue: 0,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 15,
        chestChance: 1,
        emoji: "<:Weapon_Vortex_Vanquisher:1304700656400994376>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/vortex_vanquisher.png",
    },
    "The Alley Flash": {
        name: "The Alley Flash",
        type: "Sword",
        sellPrice: 30,
        attackPower: 25,
        critChance: -10,
        critValue: 3,
        defValue: 30,
        defChance: 0,
        additionalHP: -25,
        additionalMana: 0,
        minadventurerank: 15,
        chestChance: 5,
        emoji: "<:Weapon_The_Alley_Flash:1289482689778548736>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/the_alley_flash.png",
    },
    "Lithic Blade": {
        name: "Lithic Blade",
        type: "Claymore",
        sellPrice: 30,
        attackPower: 35,
        critChance: -5,
        critValue: 1.5,
        defValue: 50,
        defChance: 0,
        additionalHP: 150,
        additionalMana: 0,
        minadventurerank: 15,
        chestChance: 5,
        emoji: "<:Weapon_Lithic_Blade:1294565079554981898>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/lithic_blade.png",
    },
    "Pro­to­type Ar­cha­ic": {
        name: "Prototype Archaic",
        type: "Claymore",
        sellPrice: 30,
        attackPower: 35,
        critChance: -10,
        critValue: -2,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 15,
        chestChance: 5,
        emoji: "<:Weapon_Prototype_Archaic:1289482979793698896>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/prototype_archaic.png",
    },
    "Black­cliff War­bow": {
        name: "Blackcliff Warbow",
        type: "Bow",
        sellPrice: 30,
        attackPower: 25,
        critChance: -10,
        critValue: 2.5,
        defValue: 0,
        defChance: 0,
        additionalHP: 50,
        additionalMana: 0,
        minadventurerank: 15,
        chestChance: 5,
        emoji: "<:Weapon_Blackcliff_Warbow:1289483143304314940>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/blackcliff_warbow.png",
    },
    Rainslasher: {
        name: "Rainslasher",
        type: "Claymore",
        sellPrice: 40,
        attackPower: 30,
        critChance: 0,
        critValue: 2.5,
        defValue: 50,
        defChance: 0,
        additionalHP: 300,
        additionalMana: 0,
        minadventurerank: 15,
        chestChance: 5,
        emoji: "<:Weapon_Rainslasher:1292670965121159250>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/rainslasher.png",
    },
    "Roy­al Gri­moire": {
        name: "Royal Grimoire",
        type: "Catalyst",
        sellPrice: 40,
        attackPower: 30,
        critChance: 0,
        critValue: 2,
        defValue: 25,
        defChance: 0,
        additionalHP: -200,
        additionalMana: 15,
        minadventurerank: 15,
        chestChance: 5,
        emoji: "<:Weapon_Royal_Grimoire:1289486411061395517>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/royal_grimoire.png",
    },
    "Eye of Perception": {
        name: "Eye of Perception",
        type: "Catalyst",
        sellPrice: 40,
        attackPower: 30,
        critChance: 20,
        critValue: 1.25,
        defValue: 50,
        defChance: 0,
        additionalHP: -50,
        additionalMana: 10,
        minadventurerank: 18,
        chestChance: 3,
        emoji: "<:Weapon_Eye_of_Perception:1291133932711972955>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/eye_of_perception.png",
    },
    "Kagotsurube Isshin": {
        name: "Kagotsurube Isshin",
        type: "Sword",
        sellPrice: 40,
        attackPower: 35,
        critChance: 15,
        critValue: 3.5,
        defValue: -100,
        defChance: 0,
        additionalHP: -25,
        additionalMana: 0,
        minadventurerank: 18,
        chestChance: 3,
        emoji: "<:Weapon_Kagotsurube_Isshin:1291134317984092262>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/kagotsurube_isshin.png",
    },
    Moonstringer: {
        name: "Moonstringer",
        type: "Rod",
        sellPrice: 0,
        attackPower: 20,
        critChance: 15,
        critValue: 1.75,
        defValue: 75,
        defChance: 0.2,
        additionalHP: 75,
        additionalMana: 0,
        minadventurerank: 20,
        chestChance: 10,
        emoji: "<:Item_Moonstringer:1309632789057896448>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/moonstringer.png",
    },
    "Amenoma Kageuchi": {
        name: "Amenoma Kageuchi",
        type: "Sword",
        sellPrice: 40,
        attackPower: 32,
        critChance: 10,
        critValue: 2,
        defValue: 20,
        defChance: -0.1,
        additionalHP: 200,
        additionalMana: 0,
        minadventurerank: 20,
        chestChance: 3,
        emoji: "<:Weapon_Amenoma_Kageuchi:1296678201065603112>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/amenoma_kageuchi.png",
    },
    Akuoumaru: {
        name: "Akuoumaru",
        type: "Claymore",
        sellPrice: 40,
        attackPower: 35,
        critChance: 15,
        critValue: 2,
        defValue: 20,
        defChance: 0,
        additionalHP: 150,
        additionalMana: 0,
        minadventurerank: 20,
        chestChance: 3,
        emoji: "<:Weapon_Akuoumaru:1303587310788411392>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/akuoumaru.png",
    },
    "Compound Bow": {
        name: "Compound Bow",
        type: "Bow",
        sellPrice: 40,
        attackPower: 40,
        critChance: 20,
        critValue: 1.5,
        defValue: 15,
        defChance: 0,
        additionalHP: 150,
        additionalMana: 0,
        minadventurerank: 20,
        chestChance: 3,
        emoji: "<:Weapon_Compound_Bow:1303587466300751912>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/compound_bow.png",
    },
    "Favonius Sword": {
        name: "Favonius Sword",
        type: "Sword",
        sellPrice: 40,
        attackPower: 50,
        critChance: 15,
        critValue: 1,
        defValue: 15,
        defChance: 0,
        additionalHP: 50,
        additionalMana: 0,
        minadventurerank: 20,
        chestChance: 3,
        emoji: "<:Weapon_Favonius_Sword:1304141989092130937>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/favonius_sword.png",
    },
    "Earth Shaker": {
        name: "Earth Shaker",
        type: "Claymore",
        sellPrice: 40,
        attackPower: 60,
        critChance: 15,
        critValue: 1.5,
        defValue: 50,
        defChance: -10,
        additionalHP: 25,
        additionalMana: 0,
        minadventurerank: 22,
        chestChance: 2,
        emoji: "<:Weapon_Earth_Shaker:1316559802046087178>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/earth_shaker.png",
    },
    Serendipity: {
        name: "Serendipity",
        type: "Rod",
        sellPrice: 0,
        attackPower: 30,
        critChance: 10,
        critValue: 1.5,
        defValue: 20,
        defChance: 0.3,
        additionalHP: 50,
        additionalMana: 0,
        minadventurerank: 25,
        chestChance: 10,
        emoji: "<:Item_Serendipity:1310102946142228573>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/serendipity.png",
    },
    "Serp­ent Spine": {
        name: "Serp­ent Spine",
        type: "Claymore",
        sellPrice: 0,
        attackPower: 50,
        critChance: 10,
        critValue: 1.5,
        defValue: 200,
        defChance: 0,
        additionalHP: -100,
        additionalMana: 0,
        minadventurerank: 25,
        chestChance: 3,
        emoji: "<:Weapon_Serpent_Spine:1310715179876483213>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/serpent_spine.png",
    },
    Absolution: {
        name: "Absolution",
        type: "Sword",
        sellPrice: 100,
        attackPower: 45,
        critChance: 25,
        critValue: 2,
        defValue: 150,
        defChance: 0.2,
        additionalHP: 350,
        additionalMana: 0,
        minadventurerank: 25,
        chestChance: 1,
        emoji: "<:Weapon_Absolution1:1303960695653535776>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/absolution.png",
    },
    "Wolf's Gravestone": {
        name: "Wolf's Gravestone",
        type: "Claymore",
        sellPrice: 100,
        attackPower: 55,
        critChance: 20,
        critValue: 1.75,
        defValue: 150,
        defChance: 0.2,
        additionalHP: -500,
        additionalMana: 0,
        minadventurerank: 25,
        chestChance: 1,
        emoji: "<:Weapon_Wolfs_Gravestone:1310711268851716247>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/wolfs_gravestone.png",
    },
    "Memory of Dust": {
        name: "Memory of Dust",
        type: "Catalyst",
        sellPrice: 100,
        attackPower: 40,
        critChance: 20,
        critValue: 1.5,
        defValue: 125,
        defChance: 0.25,
        additionalHP: 0,
        additionalMana: 15,
        minadventurerank: 25,
        chestChance: 1,
        emoji: "<:Weapon_Memory_of_Dust:1303985604060643359>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/memory_of_dust.png",
    },
    "Everlasting Moonglow": {
        name: "Everlasting Moonglow",
        type: "Catalyst",
        sellPrice: 100,
        attackPower: 5,
        critChance: 0,
        critValue: 0,
        defValue: -1000,
        defChance: -100,
        additionalHP: 2500,
        additionalMana: 15,
        minadventurerank: 29,
        chestChance: 1,
        emoji: "<:Weapon_Everlasting_Moonglow1:1317048177895014410>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/everlasting_moonglow.png",
    },
    // Reworking
    "Aqua Simulacra": {
        name: "Aqua Simulacra",
        type: "Bow",
        sellPrice: 25,
        attackPower: 0,
        critChance: -100,
        critValue: 0,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 5,
        chestChance: 0,
        emoji: "<:Weapon_Aqua_Simulacra:1283303723082190902>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/aqua_simulacra.png",
    },
    "Staff of Homa": {
        name: "Staff of Homa",
        type: "Polearm",
        sellPrice: 25,
        attackPower: 0,
        critChance: -100,
        critValue: 0,
        defValue: 0,
        defChance: 0,
        additionalHP: 0,
        additionalMana: 0,
        minadventurerank: 10,
        chestChance: 0,
        emoji: "<:Weapon_Staff_of_Homa:1283341597425008640>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/staff_of_homa.png",
    },
    // Special Weapons
    "Engulfing Lightning": {
        name: "Engulfing Lightning",
        type: "Polearm",
        sellPrice: 25,
        attackPower: 50,
        critChance: 30,
        critValue: 2.5,
        defValue: 5,
        defChance: 0.2,
        additionalHP: 100,
        additionalMana: 0,
        minadventurerank: 15,
        chestChance: 0,
        emoji: "<:Weapon_Engulfing_Lightning:1294565987710009344>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/engulfing_lightning.png",
    },
    // Ascended Weapons
    "✪ Harbinger of Dawn": {
        name: "✪ Harbinger of Dawn",
        type: "Sword",
        sellPrice: 30,
        attackPower: 40,
        critChance: 35,
        critValue: 2.5,
        defValue: 100,
        defChance: 10,
        additionalHP: 150,
        additionalMana: 0,
        minadventurerank: 20,
        chestChance: 0,
        emoji: "<:Weapon_Harbinger_of_Dawn_2nd:1317755526980964423>",
        imageURL:
            "https://lh.elara.workers.dev/rpg/weapons/asc/harbinger_of_dawn.png",
    },
    "✪ Messenger": {
        name: "✪ Messenger",
        type: "Bow",
        sellPrice: 30,
        attackPower: 75,
        critChance: 15,
        critValue: 2.75,
        defValue: -100,
        defChance: 0,
        additionalHP: -50,
        additionalMana: 0,
        minadventurerank: 20,
        chestChance: 0,
        emoji: "<:Weapon_Messenger_2nd:1317756274548408380>",
        imageURL: "https://lh.elara.workers.dev/rpg/weapons/asc/messenger.png",
    },
};

const prefixes: {
    [key: string]: (weaponData: WeaponData) => Partial<WeaponData>;
} = {
    "": (() => ({})) as (weaponData: WeaponData) => Partial<WeaponData>,
    Old: (weaponData) => ({
        attackPower: weaponData.attackPower * 0.75,
        sellPrice: Math.round(weaponData.sellPrice * 0.5),
    }),
    Sharp: (weaponData) => ({
        attackPower: weaponData.attackPower * 1.25,
        sellPrice: Math.round(weaponData.sellPrice * 1.25),
    }),
    Godly: (weaponData) => ({
        attackPower: weaponData.attackPower * 1.5,
        sellPrice: Math.round(weaponData.sellPrice * 1.5),
    }),
    Perfect: (weaponData) => ({
        attackPower: weaponData.attackPower * 2,
        sellPrice: Math.round(weaponData.sellPrice * 2),
    }),
    Worthless: (weaponData) => ({
        attackPower: weaponData.attackPower * 0.5,
        sellPrice: 0,
    }),
    Spicy: (weaponData) => ({
        critValue: weaponData.critValue * 1.5,
    }),
    Hearty: (weaponData) => ({
        additionalHP: weaponData.additionalHP * 2,
    }),
    //Specials
    Wise: (weaponData) => ({
        attackPower: weaponData.attackPower * 1.25,
        additionalHP: weaponData.additionalHP * 1.5,
        defValue: weaponData.defValue * 1.25,
        additionalMana: weaponData.additionalMana * 2,
        chestChance: 0,
    }),
    Ancient: (weaponData) => ({
        attackPower: weaponData.attackPower * 2,
        additionalHP: weaponData.additionalHP * 1.25,
        critValue: weaponData.critValue * 1.5,
        chestChance: 0,
    }),
    Clean: (weaponData) => ({
        attackPower: weaponData.attackPower * 1.5,
        defValue: weaponData.defValue * 2,
        defChance: weaponData.defChance + 10,
        chestChance: 0,
    }),
    Jaded: (weaponData) => ({
        attackPower: weaponData.attackPower * 0.75,
        critChance: weaponData.critChance + 10,
        critValue: weaponData.critValue * 2,
        chestChance: 0,
    }),
};

export const weapons = make.object<{ [key: string]: WeaponData }>();

for (const weaponName in baseWeapons) {
    const baseWeaponData = baseWeapons[weaponName];
    for (const prefix in prefixes) {
        const modifierFunction = prefixes[prefix];
        const newWeaponName = prefix ? `${prefix} ${weaponName}` : weaponName;
        const modifiedStats = modifierFunction(baseWeaponData);

        weapons[newWeaponName] = {
            ...baseWeaponData,
            name: newWeaponName,
            ...modifiedStats,
        };
    }
}

export type WeaponName = keyof typeof weapons & string;
