name: Checks
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install deps
        run: npm i
      - name: ESLint
        run: npm run lint
      - name: Prettier
        run: npm run pc
      - name: Build Code
        run: npm run build
      - name: Fixer
        run: npm run fix && git add . && git commit -m "Prettier + Linter" && git push